'use strict';

/* ============================================================
   TRADUCTIONS — FR / DE / EN
   ============================================================ */
const translations = {

  /* ==================== FRANÇAIS ==================== */
  fr: {
    'topbar.address':'Michael-Neumann-Gasse 2 - 3ème Etage, 1190 Wien',
    'topbar.hours':  'Lun–Ven : 09h30 – 16h00',
    'nav.home':      'Accueil',
    'nav.embassy':   "L'Ambassade",
    'nav.services':  'Services consulaires',
    'nav.contact':   'Contact & Horaires',
    'alert.text':    'La prise de rendez-vous est obligatoire pour toute démarche consulaire.',
    'alert.link':    'Prendre rendez-vous →',
    'hero.eyebrow':  'Service Consulaire',
    'hero.h1':       "Bienvenue à l'Ambassade de<br><em>Côte d'Ivoire</em> en Autriche",
    'hero.desc':     "Nous accompagnons les ressortissants ivoiriens résidant en Europe centrale dans toutes leurs démarches administratives et consulaires depuis Vienne.",
    'hero.btn1':     'Nos services consulaires',
    'hero.btn2':     'Prendre rendez-vous',
    'hero.card.title':'Informations pratiques',
    'hero.addr.lbl': 'Adresse',
    'hero.hours.lbl':'Horaires générales Ambassade',
    'hero.hours.val':'Lun – Ven : 09h30 – 16h00',
    'hero.tel.lbl':  'Téléphone',
    'hero.jurid.lbl':"Juridiction consulaire",
    'hero.jurid.val':"9 pays d'Europe centrale",
    'srv.badge':     'Nos services',
    'srv.title':     'Services consulaires disponibles',
    'srv.subtitle':  "L'ensemble de nos services s'adresse aux ressortissants ivoiriens et aux citoyens étrangers souhaitant visiter la Côte d'Ivoire.",
    'srv.passport':  'Passeport',
    'srv.passport.d':'Demande, renouvellement et urgence de passeport biométrique pour les ressortissants ivoiriens.',
    'srv.visa':      "Visa d'entrée",
    'srv.visa.d':    "Visas touristiques, d'affaires et de transit pour les ressortissants étrangers souhaitant entrer en Côte d'Ivoire.",
    'srv.civil':     'État civil',
    'srv.civil.d':   "Actes de naissance, de mariage, décès, transcriptions et extraits d'actes d'état civil.",
    'srv.legal':     'Légalisation',
    'srv.legal.d':   "Légalisation et apostille de documents officiels, authentification de signatures.",
    'srv.cnie':      'CNI',
    'srv.cnie.d':    "Carte nationale d'identité électronique pour les ressortissants ivoiriens en Europe centrale.",
    'srv.cert':      'Certificats & Attestations',
    'srv.cert.d':    "Certificats de vie, de résidence, de nationalité, de coutume et autres attestations officielles.",
    'srv.more':      'En savoir plus',
    'home.hours.badge': 'Horaires Ambassade',
    'info.badge':    'Horaires consulaires',
    'info.title':    "Heures d'ouverture",
    'info.subtitle': 'Le service consulaire reçoit sur rendez-vous uniquement.',
    'info.rdv':      'Prendre rendez-vous →',
    'info.ct.title': 'Nous contacter',
    'info.ct.sub':   'Pour toute question ou urgence consulaire',
    'info.addr.lbl': 'Adresse',
    'info.tel.lbl':  'Téléphone',
    'info.email.lbl':'Email consulaire',
    'info.urg.lbl':  'Urgences (hors heures)',
    'info.metro.lbl':'Accès',
    'pays.badge':    'Circonscription',
    'pays.title':    'Circonscription diplomatique',
    'pays.subtitle': "L'Ambassade de Côte d'Ivoire à Vienne exerce sa circonscription diplomatique sur 9 pays d'Europe centrale et des Balkans.",
    'actu.badge':    'Actualités',
    'actu.title':    'Informations & Annonces',
    'actu.all':      'Toutes les actualités →',
    'cta.title':     "Besoin d'assistance consulaire ?",
    'cta.desc':      "Notre équipe est à votre disposition pour vous accompagner dans toutes vos démarches administratives. Prenez rendez-vous en ligne ou contactez-nous directement.",
    'cta.btn1':      'Prendre rendez-vous',
    'cta.btn2':      'Consulter les services',
    'footer.desc':   "Ambassade de la République de Côte d'Ivoire en Autriche, desservant 9 pays d'Europe centrale. Service consulaire officiel sous l'autorité du Ministère des Affaires Étrangères.",
    'footer.srv':    'Services', 'footer.info':'Informations', 'footer.contact':'Contact',
    'footer.nav':    'Navigation',
    'footer.nav.ambassador': "L'Ambassadeur",
    'footer.nav.circonscrip': 'Circonscription diplomatique',
    'footer.nav.contact': 'Contact',
    'footer.srv.passport': 'Passeport',
    'footer.srv.visa':     'Visa',
    'footer.srv.civil':    'État civil',
    'footer.srv.legal':    'Légalisation',
    'footer.srv.cert':     'Certificats',
    'footer.legal':  'Mentions légales', 'footer.privacy':'Politique de confidentialité',
    'footer.access': 'Accessibilité', 'footer.sitemap':'Plan du site',
    'footer.copy':   '© 2025 Ambassade de la République de Côte d\'Ivoire en Autriche. Tous droits réservés.',
    /* Page Annonces */
    'ann.h1':              'Informations & Annonces',
    'ann.desc':            "Retrouvez ici toutes les informations officielles, avis importants et annonces de l'Ambassade de Côte d'Ivoire à Vienne.",
    'ann.pinned.label':    'Épinglé — Urgent',
    'ann.pinned.title':    'Fermeture exceptionnelle — Fête Nationale de Côte d\'Ivoire',
    'ann.pinned.desc':     "L'Ambassade de Côte d'Ivoire à Vienne sera <strong>fermée le vendredi 7 août 2026</strong> à l'occasion de la Fête Nationale de la République de Côte d'Ivoire (66ème anniversaire de l'indépendance). Les services reprendront normalement le lundi 10 août 2026 à 09h30.",
    'ann.pinned.date':     'Publié le 25 mai 2026',
    'ann.filter.all':      'Toutes',
    'ann.filter.urgent':   'Urgentes',
    'ann.filter.admin':    'Administratif',
    'ann.filter.event':    'Événements',
    'ann.filter.communique':'Communiqués',
    'ann.cat.mission':     'Mission économique',
    'ann.cat.diplo':       'Diplomatie',
    'ann.cat.actu':        'Actualité',
    'ann.cat.communique':  'Communiqué',
    'ann.btn.read':        ' Lire l\'article',
    'ann.btn.readfull':    ' Lire le communiqué complet',
    'ann.empty':           'Aucune annonce dans cette catégorie pour le moment.',
    'ann.sidebar.links':   'Liens utiles',
    'ann.sidebar.passport':'Renouvellement de passeport',
    'ann.sidebar.visa':    'Demande de visa',
    'ann.sidebar.civil':   'État civil',
    'ann.sidebar.rdv':     'Prendre rendez-vous',
    'ann.sidebar.hours':   "Horaires d'ouverture",
    'ann.sidebar.contact': 'Contact direct',
    'ann.sub.title':       'Recevez les annonces',
    'ann.sub.desc':        'Inscrivez-vous pour être notifié des nouvelles annonces et informations importantes.',
    'ann.sub.btn':         'S\'inscrire aux alertes',
    /* Titres & textes des annonces */
    'ann.a1.title': "Mission économique : Aka Aouélé conduit une délégation du Conseil Economique, Social, Environnemental et Culturel (Cesec) en Autriche",
    'ann.a1.desc':  "Le Président du CESEC, Aka Aouélé, a conduit une délégation ivoirienne en Autriche dans le cadre d'une mission économique visant à renforcer les échanges et la coopération entre la Côte d'Ivoire et ses partenaires européens.",
    'ann.a2.title': "La diplomatie ivoirienne à l'honneur à Vienne : la Côte d'Ivoire assure la présidence de l'Organisation du Traité d'Interdiction Complète des Essais Nucléaires",
    'ann.a2.desc':  "La Côte d'Ivoire a pris la présidence de la Commission Préparatoire de l'Organisation du Traité d'Interdiction Complète des Essais Nucléaires (CTBTO), marquant une étape majeure de la diplomatie ivoirienne sur la scène internationale à Vienne.",
    'ann.a3.title': "Nucléaire civil : La Côte d'Ivoire plaide pour un soutien appuyé de l'Agence Internationale de l'Énergie Atomique",
    'ann.a3.desc':  "La Côte d'Ivoire a exprimé à Vienne, lors des travaux de l'AIEA, sa volonté de bénéficier d'un accompagnement renforcé dans le cadre du développement de son programme nucléaire civil.",
    'ann.a4.title': "Diplomatie ivoirienne en Autriche : l'ambassadeur Cissé Yacouba échange avec le gouverneur de Vorarlberg en Autriche",
    'ann.a4.desc':  "Son Excellence Monsieur Cissé Yacouba, Ambassadeur de Côte d'Ivoire en Autriche, a rencontré le gouverneur du Land de Vorarlberg dans le cadre du renforcement des relations bilatérales entre la Côte d'Ivoire et l'Autriche.",
    'ann.a5.title': "Communiqué officiel — Présentation de lettres de créance",
    'ann.a5.desc':  "Son Excellence Monsieur Cissé Yacouba, Ambassadeur Extraordinaire et Plénipotentiaire de la République de Côte d'Ivoire, a présenté ses lettres de créance au Président fédéral de la République d'Autriche lors d'une cérémonie officielle au Palais de la Hofburg à Vienne.",
    'footer.link.amb':"→ L'Ambassadeur",
    'logo.name':     "Ambassade de Côte d'Ivoire",
    'logo.subtitle': 'République de Côte d\'Ivoire — Vienne, Autriche',
    'skip.link':     'Aller au contenu principal',
    'alert.important':'Information importante :',
    'table.day':'Jour','table.hours':'Horaires',
    'day.mon':'Lundi','day.tue':'Mardi','day.wed':'Mercredi','day.thu':'Jeudi',
    'day.fri':'Vendredi','day.sat':'Samedi','day.sun':'Dimanche','day.closed':'Fermé',
    'hours.val':'09h30 – 16h00',
    'info.note':'Fermé les jours fériés autrichiens et ivoiriens.',
    'month.jan':'Jan','month.feb':'Fév','month.mar':'Mar','month.apr':'Avr',
    'month.may':'Mai','month.jun':'Jun','month.jul':'Jul','month.aug':'Aoû',
    'month.sep':'Sep','month.oct':'Oct','month.nov':'Nov','month.dec':'Déc',
    'addr.street':'Michael-Neumann-Gasse 2 - 3ème Etage', 'pays.at':'Autriche','pays.at.cap':'Wien (siège)',
    'pays.hu':'Hongrie','pays.si':'Slovénie','pays.sk':'Slovaquie',
    'pays.hr':'Croatie','pays.rs':'Serbie','pays.ro':'Roumanie','pays.ba':'Bosnie-Herzégovine','pays.md':'Moldavie',
    'actu.tag.event':'Événement','actu.tag.info':'Information','actu.tag.mission':'Mission économique',
    'srv.badge.passport':'Document de voyage','srv.badge.visa':"Visa d'entrée",'srv.badge.identity':'Identité',
    'actu.ev1.title':"Mission économique : Visite du Président du Conseil Économique, Social, Environnemental et Culturel",
    'actu.ev1.desc': "L'Ambassade de Côte d'Ivoire à Vienne a accueilli le Président du Conseil Économique, Social, Environnemental et Culturel dans le cadre d'une mission économique visant à renforcer les liens entre la Côte d'Ivoire et l'Europe centrale.",
    'actu.ev1.date': '02 juin 2025',
    'actu.n1.title': 'Nouveau formulaire de demande de passeport',
    'actu.n1.desc':  'Mise à jour du formulaire de demande de passeport biométrique.',
    'actu.n2.title': 'Fermeture exceptionnelle — Fête du Travail',
    'actu.n2.desc':  'Le service consulaire sera fermé le 1er mai 2025 pour la Fête du Travail.',
    'actu.n3.title': 'Campagne de régularisation des ressortissants',
    'actu.n3.desc':  "L'Ambassade organise une journée dédiée à la régularisation des documents.",
    'actu.n4.title': 'Modification des délais de traitement des visas',
    'actu.n4.desc':  'Les délais de traitement des demandes de visa sont désormais de 5 à 10 jours ouvrés.',
    /* Page Services */
    'psrv.h1':       'Services Consulaires',
    'psrv.desc':     "Retrouvez l'ensemble des démarches administratives proposées par le service consulaire de l'Ambassade de Côte d'Ivoire à Vienne.",
    'psrv.appt':     'Rendez-vous obligatoire','psrv.appt.d':'Aucune démarche sans RDV préalable',
    'psrv.delay':    'Délais de traitement',   'psrv.delay.d':'Variables selon la nature du dossier',
    'psrv.pay':      'Paiements uniquement en ligne', 'psrv.pay.d':'Les frais consulaires doivent être réglés en ligne avant votre rendez-vous',
    'psrv.docs':     'Dossier complet requis', 'psrv.docs.d':'Apportez tous les documents nécessaires',
    'psrv.faq.badge':'FAQ', 'psrv.faq.title':'Questions fréquentes',
    'psrv.cta.title':"Prêt à démarrer votre démarche ?",
    'psrv.cta.desc': 'Contactez-nous pour prendre rendez-vous ou obtenir des informations complémentaires sur votre dossier.',
    'psrv.cta.btn1': 'Prendre rendez-vous', 'psrv.cta.btn2':'📞 Appeler maintenant',
    /* Services — contenu détaillé */
    'nav.annonces':          'Informations & Annonces',
    'psrv.pass.h2':          'Passeport biométrique',
    'psrv.docs.label':       'Documents requis :',
    'psrv.fees.consular':    'Frais consulaires',
    'psrv.fees.visa':        'Frais de visa',
    'psrv.fees.generic':     'Frais',
    'psrv.li.form':          'Formulaire de demande rempli et signé',
    'psrv.pass.li.birth3':   'Acte de naissance original (moins de 3 mois)',
    'psrv.pass.li.birth':    'Acte de naissance original',
    'psrv.pass.li.nat':      'Certificat de nationalité ivoirienne',
    'psrv.pass.li.nat.cert': 'Certificat de nationalité',
    'psrv.pass.li.cni.casier':'CNI valide ou extrait de casier judiciaire',
    'psrv.pass.li.cni':      'CNI valide',
    'psrv.pass.li.photos':   "2 photos d'identité couleur (fond blanc, 35×45mm)",
    'psrv.pass.li.photos.rec':"2 photos d'identité récentes",
    'psrv.pass.li.resid':    'Justificatif de résidence (moins de 3 mois)',
    'psrv.pass.li.old':      'Ancien passeport original (même expiré)',
    'psrv.pass.new.title':   'Première demande',
    'psrv.pass.new.sub':     "Pour les personnes n'ayant jamais eu de passeport",
    'psrv.pass.new.delay':   'Délai : 4 à 8 semaines selon traitement à Abidjan',
    'psrv.pass.renew.title': 'Renouvellement',
    'psrv.pass.renew.sub':   'Passeport expiré ou arrivant à expiration',
    'psrv.pass.renew.delay': 'Délai : 4 à 8 semaines',
    'psrv.pass.urg.title':   "Passeport d'urgence",
    'psrv.pass.urg.sub':     'En cas de perte, vol ou urgence avérée',
    'psrv.pass.urg.li1':     'Déclaration de perte/vol (police autrichienne)',
    'psrv.pass.urg.li5':     "Justification de l'urgence (billet d'avion, etc.)",
    'psrv.pass.urg.delay':   'Délai : 24 à 72h selon situation',
    'psrv.visa.h2':          "Visa pour la Côte d'Ivoire",
    'psrv.visa.li.pass6m':   'Passeport valide (min. 6 mois au-delà du séjour)',
    'psrv.visa.li.pass6':    'Passeport valide (min. 6 mois)',
    'psrv.visa.li.pass':     'Passeport valide',
    'psrv.visa.li.form':     'Formulaire de demande de visa rempli',
    'psrv.visa.li.lodging':  "Justificatif d'hébergement en Côte d'Ivoire",
    'psrv.visa.li.ticket':   "Billet d'avion aller-retour",
    'psrv.visa.li.ticket.rt':'Billet aller-retour',
    'psrv.visa.li.bank':     'Relevés bancaires (3 derniers mois)',
    'psrv.visa.li.insurance':'Assurance voyage valide',
    'psrv.visa.li.insur':    'Assurance voyage',
    'psrv.visa.li.invite':   "Lettre d'invitation d'une entreprise ivoirienne",
    'psrv.visa.li.kbis':     'Extrait Kbis ou registre de commerce',
    'psrv.visa.tour.title':  'Visa touristique',
    'psrv.visa.tour.sub':    "Séjour jusqu'à 90 jours",
    'psrv.visa.biz.title':   "Visa d'affaires",
    'psrv.visa.biz.sub':     'Activités professionnelles et commerciales',
    'psrv.visa.trans.title': 'Visa de transit',
    'psrv.visa.trans.sub':   'Escale sur le territoire ivoirien',
    'psrv.visa.trans.li2':   "Billet d'avion avec escale en Côte d'Ivoire",
    'psrv.visa.trans.li3':   'Visa du pays de destination finale',
    'psrv.visa.trans.li4':   'Formulaire de demande de transit',
    'psrv.visa.delay10':     'Délai : 5 à 10 jours ouvrés',
    'psrv.visa.delay5':      'Délai : 3 à 5 jours ouvrés',
    'psrv.civil.h2':         "Actes d'état civil",
    'psrv.civil.card.title': 'Actes disponibles',
    'psrv.civil.card.sub':   "Tarifs des actes d'état civil consulaires",
    'psrv.civil.li.deces':   'Acte de décès',
    'psrv.civil.li.mariage': 'Acte de mariage',
    'psrv.civil.li.admin':   'Attestation Administrative',
    'psrv.civil.li.renon':   'Attestation de renonciation à la nationalité',
    'psrv.civil.li.cic':     "Carte d'identité consulaire",
    'psrv.civil.li.celeb':   'Célébration de mariage',
    'psrv.civil.li.vie':     'Certificat de vie',
    'psrv.civil.li.naiss':   'Extrait de naissance',
    'psrv.civil.li.lp':      'Laissez-passer pour départ volontaire',
    'psrv.civil.li.legal.adm':'Légalisation de documents administratifs',
    'psrv.civil.li.legal.ent':'Légalisation de documents pour Entreprises',
    'psrv.civil.li.trans':   "Transcription actes d'État Civil",
    'psrv.civil.docs.title': '📋 Documents communs requis',
    'psrv.civil.docs.li1':   "Pièce d'identité valide (CNI ou passeport)",
    'psrv.civil.docs.li2':   "Justificatif de lien de parenté ou d'état (selon acte)",
    'psrv.civil.docs.li3':   'Documents originaux à transcrir/corriger',
    'psrv.civil.note':       'Note :',
    'psrv.civil.note.text':  "Les actes établis à l'étranger nécessitent une traduction certifiée conforme en français par un traducteur assermenté.",
    'psrv.legal.h2':         'Légalisation de documents',
    'psrv.legal.sub':        "La légalisation est l'acte par lequel l'ambassade atteste de l'authenticité d'un document officiel.",
    'psrv.legal.ivo.title':  'Documents ivoiriens',
    'psrv.legal.ivo.sub':    'Légalisation pour usage en Europe',
    'psrv.legal.ivo.li1':    'Document original ivoirien avec signature officielle',
    'psrv.legal.li.id':      "Pièce d'identité du demandeur",
    'psrv.legal.li.form':    'Formulaire de légalisation rempli',
    'psrv.legal.li.id.valid':"Pièce d'identité valide",
    'psrv.legal.per.doc':    'document',
    'psrv.legal.per.sig':    'signature',
    'psrv.legal.per.copy':   'copie',
    'psrv.legal.sig.title':  'Authentification de signature',
    'psrv.legal.sig.sub':    "Certification de l'authenticité d'une signature",
    'psrv.legal.sig.li1':    'Document original à authentifier',
    'psrv.legal.sig.li2':    'Présence obligatoire du signataire',
    'psrv.legal.copy.title': 'Copie certifiée conforme',
    'psrv.legal.copy.sub':   "Certification qu'une copie est conforme à l'original",
    'psrv.legal.copy.li1':   'Document original à certifier',
    'psrv.legal.copy.li3':   'Photocopie à certifier',
    'psrv.cert.h2':          'Certificats & Attestations',
    'psrv.cert.card.sub':    'Tarifs des certificats et attestations consulaires',
    'psrv.cert.li.celib':    'Certificat de célibat',
    'psrv.cert.li.res':      'Certificat de résidence',
    'psrv.cert.li.cout':     'Certificat de coutume',
    'psrv.cert.li.proc':     'Procuration',
    'psrv.faq.q1': 'Faut-il absolument un rendez-vous ?',
    'psrv.faq.a1': "Oui, la prise de rendez-vous est obligatoire pour tout dépôt de dossier. Aucun dossier ne sera accepté sans rendez-vous préalable. Vous pouvez prendre rendez-vous par téléphone ou par email.",
    'psrv.faq.q2': "Combien de temps dure le traitement d'un passeport ?",
    'psrv.faq.a2': "Le délai moyen de traitement d'un passeport biométrique est de 4 à 8 semaines. Ce délai dépend des conditions de traitement à Abidjan. En cas d'urgence dûment justifiée, un passeport d'urgence peut être délivré sous 24 à 72 heures.",
    'psrv.faq.q3': 'Les frais sont-ils remboursables en cas de refus ?',
    'psrv.faq.a3': "Non, les frais consulaires sont non remboursables, y compris en cas de refus de la demande. Il est donc important de s'assurer que votre dossier est complet avant de le déposer.",
    'psrv.faq.q4': 'Puis-je envoyer mon dossier par courrier postal ?',
    'psrv.faq.a4': "Pour certaines demandes simples (légalisation de copies, certains certificats), l'envoi par courrier recommandé est possible. Pour les demandes de passeport et de CNI, la présence physique du demandeur est obligatoire pour la prise d'empreintes biométriques.",
    'psrv.faq.q5': 'Je réside en Hongrie, puis-je effectuer mes démarches à Vienne ?',
    'psrv.faq.a5': "Oui, l'Ambassade de Côte d'Ivoire à Vienne est compétente pour tous les ressortissants ivoiriens résidant en Autriche, Hongrie, Slovénie, Slovaquie, Croatie, Serbie, Roumanie et Bosnie-Herzégovine. Vous devez vous déplacer à Vienne pour effectuer vos démarches.",
    /* Page Contact */
    'pcon.h1':       'Contact & Horaires',
    'pcon.desc':     "Coordonnées complètes et horaires d'ouverture du service consulaire. Toute démarche nécessite un rendez-vous préalable.",
    'pcon.tel.lbl':  'Téléphone',   'pcon.email.lbl':'Email consulaire',
    'pcon.addr.lbl': 'Adresse',     'pcon.urg.lbl':'Urgences consulaires',
    'pcon.urg.sub':  'Disponible 24h/24 pour urgences',
    'pcon.h.badge':  'Horaires consulaires',    'pcon.h.title':"Heures d'ouverture",
    'pcon.a.badge':  'Accès',       'pcon.a.title':'Comment nous trouver',
    'pcon.f.badge':  'Nous écrire', 'pcon.f.title':'Formulaire de contact',
    'pcon.f.desc':   'Pour toute question ou demande de rendez-vous, remplissez ce formulaire. Nous vous répondrons sous 3 à 5 jours ouvrés.',
    'pcon.f.send':   'Envoyer le message →',
    'pcon.table.window':'Guichet consulaire',
    'pcon.urg2.title':'🚨 Urgences consulaires',
    'pcon.urg2.desc': "En cas d'urgence en dehors des heures d'ouverture (perte de passeport, décès, hospitalisation, arrestation), notre service de permanence est disponible 24h/24.",
    'pcon.phone.hours':   'Lun – Ven : 09h30 – 16h00',
    'pcon.email.reply':   'Réponse sous 1–2 jours ouvrés',
    'pcon.addr.official': '📍 Adresse géographique',
    'pcon.h.depot.title': 'Dépôt de dossiers',
    'pcon.h.depot.sub':   'Documents & formulaires',
    'pcon.h.days':        'Mardi – Vendredi',
    'pcon.h.closed':      'Lundi · Samedi · Dimanche — <strong style="color:#e53e3e;">Fermé</strong>',
    'pcon.h.retrait.title':'Retraits de dossiers',
    'pcon.h.retrait.sub': 'Sur rendez-vous uniquement',
    'pcon.h.feries':      'Quelques jours fériés',
    'pcon.h.new-year':    'Nouvel An',
    'pcon.h.labour':      'Fête du Travail (AT & CI)',
    'pcon.h.ci-national': "Fête Nationale de Côte d'Ivoire",
    'pcon.h.at-national': 'Fête Nationale autrichienne',
    'pcon.h.xmas':        'Noël',
    'pcon.a.metro':       '🚇 Métro (U-Bahn)',
    'pcon.a.metro.desc':  'Ligne <strong>U4</strong> — Station <strong>Heiligenstadt</strong>',
    'pcon.a.tram':        '🚋 Tramway (Straßenbahn)',
    'pcon.a.tram.desc':   'Ligne <strong>D</strong> — Arrêt <strong>Grinzinger Straße / Döblinger Hauptstraße</strong>',
    'pcon.a.bus':         '🚌 Bus',
    'pcon.a.bus.desc':    'Lignes <strong>35A</strong> — Arrêt <strong>Michael-Neumann-Gasse</strong>',
    'pcon.a.parking':     '🅿️ Stationnement',
    'pcon.a.parking.desc':'Stationnement possible dans les rues environnantes du 19ème arrondissement.',
    'pcon.map.desc':      "Carte interactive — Ambassade de Côte d'Ivoire à Vienne",
    'pcon.map.btn':       'Ouvrir dans Google Maps →',
    'pcon.f.before.title':'Avant de contacter',
    'pcon.f.before.1':    'Vérifiez que vous avez consulté la liste des documents requis',
    'pcon.f.before.2':    'Précisez clairement la nature de votre demande',
    'pcon.f.before.3':    'Indiquez votre pays de résidence actuel',
    'pcon.f.before.4':    "Pour les urgences, appelez directement le numéro d'urgence",
    'pcon.f.delays.title':'Délais de réponse',
    'pcon.f.delay.email': 'Email / formulaire',
    'pcon.f.delay.email.val':'3–5 jours ouvrés',
    'pcon.f.delay.rdv':   'Demande de RDV',
    'pcon.f.delay.rdv.val':'48h ouvrées',
    'pcon.f.delay.urg.val':'Immédiat (tél.)',
    'pcon.f.form.title':  'Envoyez-nous un message',
    'pcon.f.prenom':      'Prénom',
    'pcon.f.nom':         'Nom',
    'pcon.f.email':       'Adresse email',
    'pcon.f.tel':         'Téléphone',
    'pcon.f.pays':        'Pays de résidence',
    'pcon.f.objet':       'Objet de la demande',
    'pcon.f.message':     'Message',
    'pcon.f.select.pays': '— Sélectionner un pays —',
    'pcon.f.select.objet':'— Sélectionner un type de demande —',
    'pcon.f.opt.rdv':     'Prise de rendez-vous',
    'pcon.f.opt.passport':'Passeport',
    'pcon.f.opt.visa':    'Visa',
    'pcon.f.opt.civil':   'État civil',
    'pcon.f.opt.legal':   'Légalisation de documents',
    'pcon.f.opt.cnie':    'CNI',
    'pcon.f.opt.cert':    'Certificat / Attestation',
    'pcon.f.opt.urgent':  'Urgence consulaire',
    'pcon.f.opt.other':   'Autre demande',
    'pcon.f.rgpd':        "J'accepte que mes données soient utilisées dans le cadre du traitement de ma demande consulaire, conformément au RGPD.",
    'pcon.urg2.label':    'Urgences consulaires',
    'pcon.urg2.avail':    'Disponible 24h/24 — 7j/7',
    /* Page Ambassade */
    'pamb.h1':       "Ambassade de Côte d'Ivoire",
    'pamb.desc':     "Représentation officielle de la République de Côte d'Ivoire en Autriche depuis Vienne, assurant les relations diplomatiques et les services consulaires pour 9 pays d'Europe centrale.",
    'pamb.mis.badge':'Notre mission', 'pamb.mis.title':'Mission diplomatique & consulaire',
    'pamb.pays.badge':'Juridiction', 'pamb.pays.title':'Circonscription diplomatique',
    'pamb.pays.sub': "L'Ambassade de Côte d'Ivoire à Vienne couvre la circonscription diplomatique des 9 pays suivants.",
    'pamb.amb.badge':'Direction',    'pamb.rel.badge':'Diplomatie',
    'pamb.rel.title':"Relations Côte d'Ivoire — Autriche",
    'pamb.ci.badge': "La Côte d'Ivoire", 'pamb.ci.title':"Découvrir la Côte d'Ivoire",
    'pamb.ci.p1':   "La République de Côte d'Ivoire est un pays d'Afrique de l'Ouest, bordé au sud par le Golfe de Guinée. Première économie de l'Union Économique et Monétaire Ouest-Africaine (UEMOA), elle est le premier producteur mondial de cacao.",
    'pamb.ci.p2':   "Abidjan, capitale économique, est l'une des métropoles les plus dynamiques d'Afrique subsaharienne. Yamoussoukro est la capitale politique et administrative du pays.",
    'pamb.ci.stat.area':'Superficie', 'pamb.ci.stat.pop':'Population',
    'pamb.ci.stat.lang':'Langue officielle', 'pamb.ci.stat.lang.val':'Français',
    'pamb.ci.stat.currency':'Monnaie', 'pamb.ci.stat.indep':'Indépendance',
    'pamb.ci.stat.indep.val':'7 août 1960', 'pamb.ci.stat.capital':'Capitale polit.',
    'pamb.ci.republic':"République de Côte d'Ivoire",
    'pamb.mis.p1':   "L'Ambassade de la République de Côte d'Ivoire en Autriche est la représentation diplomatique officielle de la Côte d'Ivoire à Vienne. Elle assure la défense des intérêts ivoiriens, le développement des relations bilatérales et la protection de ses ressortissants.",
    'pamb.mis.p2':   "Établie conformément à la Convention de Vienne sur les relations diplomatiques de 1961, l'Ambassade remplit une double mission : diplomatique (représentation de l'État auprès du pays hôte) et consulaire (assistance aux ressortissants ivoiriens résidant dans sa juridiction).",
    'pamb.mis.p3':   "Au titre de sa compétence territoriale, l'Ambassade couvre 9 pays : l'Autriche, la Hongrie, la Slovénie, la Slovaquie, la Croatie, la Serbie, la Roumanie et la Bosnie-Herzégovine.",
    'pamb.stat.countries':'pays dans la Circonscription diplomatique', 'pamb.stat.conv':'Conv. de Vienne', 'pamb.stat.ci':"Côte d'Ivoire", 'pamb.stat.host':'Pays hôte',
    'pamb.amb.title':"Ambassadeur Extraordinaire et Plénipotentiaire de la République de Côte d'Ivoire en Autriche",
    'pamb.amb.p1':   "Son Excellence Monsieur Cissé Yacouba est accrédité auprès de la République d'Autriche en qualité d'Ambassadeur Extraordinaire et Plénipotentiaire de la République de Côte d'Ivoire. Il est également accrédité auprès de la Hongrie, la Slovénie, la Slovaquie, la Croatie, la Serbie, la Roumanie et la Bosnie-Herzégovine.",
    'pamb.amb.p2':   "Fort d'une longue carrière diplomatique au service de la Côte d'Ivoire, Son Excellence Monsieur Cissé Yacouba représente les intérêts de la République ivoirienne, promeut les relations bilatérales et multilatérales, et coordonne l'ensemble des services de l'Ambassade.",
  },

  /* ==================== DEUTSCH ==================== */
  de: {
    'topbar.address':'Michael-Neumann-Gasse 2 - 3. Stock, 1190 Wien',
    'topbar.hours':  'Mo–Fr : 09:30 – 16:00 Uhr',
    'nav.home':      'Startseite',
    'nav.embassy':   'Die Botschaft',
    'nav.services':  'Konsularische Dienste',
    'nav.contact':   'Kontakt & Öffnungszeiten',
    'alert.text':    'Eine Terminvereinbarung ist für alle konsularischen Angelegenheiten erforderlich.',
    'alert.link':    'Termin vereinbaren →',
    'hero.eyebrow':  'Konsulardienst',
    'hero.h1':       "Willkommen bei der Botschaft der<br><em>Elfenbeinküste</em> in Österreich",
    'hero.desc':     "Wir begleiten ivorische Staatsangehörige in Mitteleuropa bei allen administrativen und konsularischen Angelegenheiten von Wien aus.",
    'hero.btn1':     'Unsere Dienste',
    'hero.btn2':     'Termin vereinbaren',
    'hero.card.title':'Praktische Informationen',
    'hero.addr.lbl': 'Adresse',
    'hero.hours.lbl':'Allgemeine Botschaftszeiten',
    'hero.hours.val':'Mo – Fr : 09:30 – 16:00 Uhr',
    'hero.tel.lbl':  'Telefon',
    'hero.jurid.lbl':'Konsularer Zuständigkeitsbereich',
    'hero.jurid.val':'9 mitteleuropäische Länder',
    'srv.badge':     'Unsere Dienste',
    'srv.title':     'Verfügbare konsularische Dienste',
    'srv.subtitle':  'Alle unsere Dienste richten sich an ivorische Staatsangehörige und ausländische Bürger, die die Elfenbeinküste besuchen möchten.',
    'srv.passport':  'Reisepass',
    'srv.passport.d':'Erstantrag, Verlängerung und Notreisepass für ivorische Staatsangehörige.',
    'srv.visa':      'Einreisevisum',
    'srv.visa.d':    'Touristenvisa, Geschäftsvisa und Transitvisa für ausländische Staatsangehörige.',
    'srv.civil':     'Personenstandswesen',
    'srv.civil.d':   'Geburtsurkunden, Heiratsurkunden, Sterbeurkunden und Abschriften.',
    'srv.legal':     'Beglaubigung',
    'srv.legal.d':   'Beglaubigung offizieller Dokumente, Apostille und Unterschriftsbeglaubigung.',
    'srv.cnie':      'Elektronischer Personalausweis',
    'srv.cnie.d':    'Nationaler elektronischer Personalausweis für ivorische Staatsangehörige in Mitteleuropa.',
    'srv.cert':      'Bescheinigungen & Atteste',
    'srv.cert.d':    'Lebensbescheinigungen, Wohnsitzbescheinigungen, Staatsangehörigkeitsnachweise.',
    'srv.more':      'Mehr erfahren',
    'home.hours.badge': 'Öffnungszeiten der Botschaft',
    'info.badge':    'Konsularische Öffnungszeiten',
    'info.title':    'Öffnungszeiten',
    'info.subtitle': 'Der Konsulardienst empfängt nur nach vorheriger Terminvereinbarung.',
    'info.rdv':      'Termin vereinbaren →',
    'info.ct.title': 'Kontakt aufnehmen',
    'info.ct.sub':   'Für Fragen oder konsularische Notfälle',
    'info.addr.lbl': 'Adresse',     'info.tel.lbl':'Telefon',
    'info.email.lbl':'Konsularische E-Mail', 'info.urg.lbl':'Notfall (außerhalb der Öffnungszeiten)',
    'info.metro.lbl':'Anfahrt',
    'pays.badge':    'Amtsbereich',
    'pays.title':    'Diplomatischer Amtsbereich',
    'pays.subtitle': 'Die Botschaft der Elfenbeinküste in Wien ist für Staatsangehörige zuständig, die in den folgenden 9 Ländern leben.',
    'actu.badge':    'Aktuelles',
    'actu.title':    'Informationen & Ankündigungen',
    'actu.all':      'Alle Nachrichten →',
    'cta.title':     'Benötigen Sie konsularische Hilfe?',
    'cta.desc':      'Unser Team steht Ihnen für alle administrativen Angelegenheiten zur Verfügung. Vereinbaren Sie online einen Termin oder kontaktieren Sie uns direkt.',
    'cta.btn1':      'Termin vereinbaren', 'cta.btn2':'Dienste ansehen',
    'footer.desc':   "Botschaft der Republik Côte d'Ivoire in Österreich, zuständig für 9 mitteleuropäische Länder. Konsulardienst.",
    'footer.srv':    'Dienste', 'footer.info':'Informationen', 'footer.contact':'Kontakt',
    'footer.nav':    'Navigation',
    'footer.nav.ambassador': 'Der Botschafter',
    'footer.nav.circonscrip': 'Diplomatischer Amtsbereich',
    'footer.nav.contact': 'Kontakt',
    'footer.srv.passport': 'Reisepass',
    'footer.srv.visa':     'Visum',
    'footer.srv.civil':    'Personenstandswesen',
    'footer.srv.legal':    'Beglaubigung',
    'footer.srv.cert':     'Bescheinigungen',
    'footer.legal':  'Impressum', 'footer.privacy':'Datenschutz',
    'footer.access': 'Barrierefreiheit', 'footer.sitemap':'Sitemap',
    'footer.copy':   '© 2025 Botschaft der Republik Côte d\'Ivoire in Österreich. Alle Rechte vorbehalten.',
    'footer.link.amb':'→ Der Botschafter',
    /* Page Annonces */
    'ann.h1':              'Informationen & Ankündigungen',
    'ann.desc':            'Hier finden Sie alle offiziellen Informationen, wichtigen Mitteilungen und Ankündigungen der Botschaft der Elfenbeinküste in Wien.',
    'ann.pinned.label':    'Angeheftet — Dringend',
    'ann.pinned.title':    'Außerordentliche Schließung — Nationalfeiertag der Elfenbeinküste',
    'ann.pinned.desc':     'Die Botschaft der Elfenbeinküste in Wien ist am <strong>Freitag, 7. August 2026</strong> anlässlich des Nationalfeiertags der Republik Côte d\'Ivoire (66. Jahrestag der Unabhängigkeit) geschlossen. Die Dienste werden am Montag, 10. August 2026 um 09:30 Uhr wieder normal aufgenommen.',
    'ann.pinned.date':     'Veröffentlicht am 25. Mai 2026',
    'ann.filter.all':      'Alle',
    'ann.filter.urgent':   'Dringend',
    'ann.filter.admin':    'Verwaltung',
    'ann.filter.event':    'Veranstaltungen',
    'ann.filter.communique':'Mitteilungen',
    'ann.cat.mission':     'Wirtschaftsmission',
    'ann.cat.diplo':       'Diplomatie',
    'ann.cat.actu':        'Aktuell',
    'ann.cat.communique':  'Mitteilung',
    'ann.btn.read':        ' Artikel lesen',
    'ann.btn.readfull':    ' Vollständige Mitteilung lesen',
    'ann.empty':           'Derzeit keine Ankündigungen in dieser Kategorie.',
    'ann.sidebar.links':   'Nützliche Links',
    'ann.sidebar.passport':'Passverlängerung',
    'ann.sidebar.visa':    'Visumantrag',
    'ann.sidebar.civil':   'Standesamt',
    'ann.sidebar.rdv':     'Termin vereinbaren',
    'ann.sidebar.hours':   'Öffnungszeiten',
    'ann.sidebar.contact': 'Direktkontakt',
    'ann.sub.title':       'Ankündigungen erhalten',
    'ann.sub.desc':        'Melden Sie sich an, um über neue Ankündigungen und wichtige Informationen benachrichtigt zu werden.',
    'ann.sub.btn':         'Für Benachrichtigungen anmelden',
    /* Titel & Texte der Ankündigungen */
    'ann.a1.title': 'Wirtschaftsmission: Aka Aouélé leitet eine Delegation des Wirtschafts-, Sozial-, Umwelt- und Kulturrats (CESEC) nach Österreich',
    'ann.a1.desc':  'Der Präsident des CESEC, Aka Aouélé, hat eine ivorische Delegation nach Österreich geführt, um den Austausch und die Zusammenarbeit zwischen der Elfenbeinküste und ihren europäischen Partnern zu stärken.',
    'ann.a2.title': 'Die ivorische Diplomatie geehrt in Wien: Die Elfenbeinküste übernimmt den Vorsitz der Organisation des Vertrags über das umfassende Verbot von Nuklearversuchen (CTBTO)',
    'ann.a2.desc':  'Die Elfenbeinküste hat den Vorsitz der Vorbereitungskommission der Organisation des Vertrags über das umfassende Verbot von Nuklearversuchen (CTBTO) übernommen, ein bedeutender Meilenstein der ivorischen Diplomatie auf der internationalen Bühne in Wien.',
    'ann.a3.title': 'Zivile Kernkraft: Die Elfenbeinküste setzt sich für eine verstärkte Unterstützung der Internationalen Atomenergiebehörde (IAEA) ein',
    'ann.a3.desc':  'Die Elfenbeinküste hat bei den Arbeiten der IAEA in Wien ihren Wunsch geäußert, verstärkte Unterstützung für die Entwicklung ihres zivilen Atomprogramms zu erhalten.',
    'ann.a4.title': 'Ivorische Diplomatie in Österreich: Botschafter Cissé Yacouba trifft den Landeshauptmann von Vorarlberg',
    'ann.a4.desc':  'Seine Exzellenz Herr Cissé Yacouba, Botschafter der Elfenbeinküste in Österreich, hat den Landeshauptmann des Bundeslandes Vorarlberg im Rahmen der Stärkung der bilateralen Beziehungen zwischen der Elfenbeinküste und Österreich getroffen.',
    'ann.a5.title': 'Offizielle Mitteilung — Überreichung der Beglaubigungsschreiben',
    'ann.a5.desc':  'Seine Exzellenz Herr Cissé Yacouba, Außerordentlicher und Bevollmächtigter Botschafter der Republik Côte d\'Ivoire, hat dem Bundespräsidenten der Republik Österreich sein Beglaubigungsschreiben bei einer offiziellen Zeremonie im Hofburg-Palast in Wien überreicht.',
    'logo.name':     'Botschaft der Elfenbeinküste',
    'logo.subtitle': 'Republik Côte d\'Ivoire — Wien, Österreich',
    'skip.link':     'Zum Hauptinhalt springen',
    'alert.important':'Wichtiger Hinweis:',
    'table.day':'Tag','table.hours':'Öffnungszeiten',
    'day.mon':'Montag','day.tue':'Dienstag','day.wed':'Mittwoch','day.thu':'Donnerstag',
    'day.fri':'Freitag','day.sat':'Samstag','day.sun':'Sonntag','day.closed':'Geschlossen',
    'hours.val':'09:30 – 16:00 Uhr',
    'info.note':'Geschlossen an österreichischen und ivorischen Feiertagen.',
    'month.jan':'Jan','month.feb':'Feb','month.mar':'Mär','month.apr':'Apr',
    'month.may':'Mai','month.jun':'Jun','month.jul':'Jul','month.aug':'Aug',
    'month.sep':'Sep','month.oct':'Okt','month.nov':'Nov','month.dec':'Dez',
    'addr.street':'Michael-Neumann-Gasse 2 - 3. Stock', 'pays.at':'Österreich','pays.at.cap':'Wien (Sitz)',
    'pays.hu':'Ungarn','pays.si':'Slowenien','pays.sk':'Slowakei',
    'pays.hr':'Kroatien','pays.rs':'Serbien','pays.ro':'Rumänien','pays.ba':'Bosnien und Herzegowina','pays.md':'Moldawien',
    'actu.tag.event':'Veranstaltung','actu.tag.info':'Information','actu.tag.mission':'Wirtschaftsmission',
    'actu.ev1.title':'Wirtschaftsmission: Besuch des Präsidenten des Wirtschafts-, Sozial-, Umwelt- und Kulturrats',
    'actu.ev1.desc': 'Die Botschaft der Elfenbeinküste in Wien empfing den Präsidenten des Wirtschafts-, Sozial-, Umwelt- und Kulturrats im Rahmen einer Wirtschaftsmission zur Stärkung der Beziehungen zwischen der Elfenbeinküste und Mitteleuropa.',
    'actu.ev1.date': '2. Juni 2025',
    'actu.n1.title': 'Neues Antragsformular für den Reisepass',
    'actu.n1.desc':  'Aktualisierung des Antragsformulars für den biometrischen Reisepass.',
    'actu.n2.title': 'Außerordentliche Schließung — Tag der Arbeit',
    'actu.n2.desc':  'Der Konsulardienst ist am 1. Mai 2025 anlässlich des Tags der Arbeit geschlossen.',
    'actu.n3.title': 'Regularisierungskampagne für Staatsangehörige',
    'actu.n3.desc':  'Die Botschaft organisiert einen Tag zur Regularisierung von Dokumenten.',
    'actu.n4.title': 'Änderung der Visabearbeitungszeiten',
    'actu.n4.desc':  'Die Bearbeitungszeiten für Visaanträge betragen nun 5 bis 10 Werktage.',
    'psrv.h1':       'Konsularische Dienste',
    'psrv.desc':     'Alle konsularischen Verfahren der Botschaft der Elfenbeinküste in Wien.',
    'psrv.appt':     'Termin erforderlich',  'psrv.appt.d':'Kein Verfahren ohne vorherigen Termin',
    'psrv.delay':    'Bearbeitungszeiten',   'psrv.delay.d':'Variiert je nach Dossier',
    'psrv.pay':      'Zahlungen ausschließlich online', 'psrv.pay.d':'Alle Konsulargebühren sind vor dem Termin online zu bezahlen',
    'psrv.docs':     'Vollständige Unterlagen erforderlich', 'psrv.docs.d':'Bringen Sie alle Dokumente mit',
    'psrv.faq.badge':'FAQ', 'psrv.faq.title':'Häufig gestellte Fragen',
    'psrv.cta.title':'Bereit, Ihr Verfahren zu starten?',
    'psrv.cta.desc': 'Kontaktieren Sie uns für einen Termin oder für Informationen zu Ihrem Dossier.',
    'psrv.cta.btn1': 'Termin vereinbaren', 'psrv.cta.btn2':'📞 Jetzt anrufen',
    /* Dienste — detaillierter Inhalt */
    'nav.annonces':          'Informationen & Ankündigungen',
    'psrv.pass.h2':          'Biometrischer Reisepass',
    'psrv.docs.label':       'Erforderliche Dokumente:',
    'psrv.fees.consular':    'Konsulargebühren',
    'psrv.fees.visa':        'Visagebühren',
    'psrv.fees.generic':     'Gebühren',
    'psrv.li.form':          'Antragsformular ausgefüllt und unterschrieben',
    'psrv.pass.li.birth3':   'Geburtsurkunde im Original (weniger als 3 Monate alt)',
    'psrv.pass.li.birth':    'Geburtsurkunde im Original',
    'psrv.pass.li.nat':      'Ivorische Staatsangehörigkeitsbescheinigung',
    'psrv.pass.li.nat.cert': 'Staatsangehörigkeitsbescheinigung',
    'psrv.pass.li.cni.casier':'Gültiger Personalausweis oder polizeiliches Führungszeugnis',
    'psrv.pass.li.cni':      'Gültiger Personalausweis',
    'psrv.pass.li.photos':   '2 Passfotos (weißer Hintergrund, 35×45mm)',
    'psrv.pass.li.photos.rec':'2 aktuelle Passfotos',
    'psrv.pass.li.resid':    'Wohnsitznachweis (weniger als 3 Monate alt)',
    'psrv.pass.li.old':      'Alter Reisepass im Original (auch abgelaufene akzeptiert)',
    'psrv.pass.new.title':   'Erstantrag',
    'psrv.pass.new.sub':     'Für Personen, die noch nie einen Reisepass hatten',
    'psrv.pass.new.delay':   'Bearbeitungszeit: 4 bis 8 Wochen je nach Bearbeitung in Abidjan',
    'psrv.pass.renew.title': 'Verlängerung',
    'psrv.pass.renew.sub':   'Abgelaufener oder bald ablaufender Reisepass',
    'psrv.pass.renew.delay': 'Bearbeitungszeit: 4 bis 8 Wochen',
    'psrv.pass.urg.title':   'Notreisepass',
    'psrv.pass.urg.sub':     'Bei Verlust, Diebstahl oder nachgewiesenem Notfall',
    'psrv.pass.urg.li1':     'Verlust-/Diebstahlmeldung (österreichische Polizei)',
    'psrv.pass.urg.li5':     'Nachweis der Dringlichkeit (Flugticket usw.)',
    'psrv.pass.urg.delay':   'Bearbeitungszeit: 24 bis 72 Stunden je nach Situation',
    'psrv.visa.h2':          "Visum für die Elfenbeinküste",
    'psrv.visa.li.pass6m':   'Gültiger Reisepass (mind. 6 Monate über den Aufenthalt hinaus)',
    'psrv.visa.li.pass6':    'Gültiger Reisepass (mind. 6 Monate)',
    'psrv.visa.li.pass':     'Gültiger Reisepass',
    'psrv.visa.li.form':     'Ausgefülltes Visaantragsformular',
    'psrv.visa.li.lodging':  'Unterkunftsnachweis in der Elfenbeinküste',
    'psrv.visa.li.ticket':   'Hin- und Rückflugticket',
    'psrv.visa.li.ticket.rt':'Hin- und Rückflugticket',
    'psrv.visa.li.bank':     'Kontoauszüge (letzte 3 Monate)',
    'psrv.visa.li.insurance':'Gültige Reiseversicherung',
    'psrv.visa.li.insur':    'Reiseversicherung',
    'psrv.visa.li.invite':   'Einladungsschreiben eines ivorischen Unternehmens',
    'psrv.visa.li.kbis':     'Handelsregisterauszug',
    'psrv.visa.tour.title':  'Touristenvisum',
    'psrv.visa.tour.sub':    'Aufenthalt bis zu 90 Tagen',
    'psrv.visa.biz.title':   'Geschäftsvisum',
    'psrv.visa.biz.sub':     'Berufliche und geschäftliche Tätigkeiten',
    'psrv.visa.trans.title': 'Transitvisum',
    'psrv.visa.trans.sub':   'Zwischenstopp im ivorischen Hoheitsgebiet',
    'psrv.visa.trans.li2':   'Flugticket mit Zwischenstopp in der Elfenbeinküste',
    'psrv.visa.trans.li3':   'Visum des Ziellandes',
    'psrv.visa.trans.li4':   'Ausgefülltes Transitantragsformular',
    'psrv.visa.delay10':     'Bearbeitungszeit: 5 bis 10 Werktage',
    'psrv.visa.delay5':      'Bearbeitungszeit: 3 bis 5 Werktage',
    'psrv.civil.h2':         'Personenstandsurkunden',
    'psrv.civil.card.title': 'Verfügbare Urkunden',
    'psrv.civil.card.sub':   'Gebühren für konsularische Personenstandsurkunden',
    'psrv.civil.li.deces':   'Sterbeurkunde',
    'psrv.civil.li.mariage': 'Heiratsurkunde',
    'psrv.civil.li.admin':   'Verwaltungsbescheinigung',
    'psrv.civil.li.renon':   'Erklärung über den Verzicht auf die Staatsangehörigkeit',
    'psrv.civil.li.cic':     'Konsularischer Personalausweis',
    'psrv.civil.li.celeb':   'Eheschließung',
    'psrv.civil.li.vie':     'Lebensbescheinigung',
    'psrv.civil.li.naiss':   'Geburtsauszug',
    'psrv.civil.li.lp':      'Laissez-passer für freiwillige Ausreise',
    'psrv.civil.li.legal.adm':'Beglaubigung von Verwaltungsdokumenten',
    'psrv.civil.li.legal.ent':'Beglaubigung von Unternehmensdokumenten',
    'psrv.civil.li.trans':   'Transkription von Personenstandsurkunden',
    'psrv.civil.docs.title': '📋 Gemeinsam erforderliche Dokumente',
    'psrv.civil.docs.li1':   'Gültiger Lichtbildausweis (Personalausweis oder Reisepass)',
    'psrv.civil.docs.li2':   'Nachweis des Verwandtschaftsverhältnisses oder Personenstands (je nach Urkunde)',
    'psrv.civil.docs.li3':   'Zu transkribierende/korrigierende Originaldokumente',
    'psrv.civil.note':       'Hinweis:',
    'psrv.civil.note.text':  'Im Ausland ausgestellte Urkunden benötigen eine beglaubigte Übersetzung ins Französische durch einen vereidigten Übersetzer.',
    'psrv.legal.h2':         'Beglaubigung von Dokumenten',
    'psrv.legal.sub':        'Die Beglaubigung ist der Akt, durch den die Botschaft die Echtheit eines offiziellen Dokuments bestätigt.',
    'psrv.legal.ivo.title':  'Ivorische Dokumente',
    'psrv.legal.ivo.sub':    'Beglaubigung für die Verwendung in Europa',
    'psrv.legal.ivo.li1':    'Ivorisches Originaldokument mit offizieller Unterschrift',
    'psrv.legal.li.id':      'Lichtbildausweis des Antragstellers',
    'psrv.legal.li.form':    'Ausgefülltes Beglaubigungsformular',
    'psrv.legal.li.id.valid':'Gültiger Lichtbildausweis',
    'psrv.legal.per.doc':    'Dokument',
    'psrv.legal.per.sig':    'Unterschrift',
    'psrv.legal.per.copy':   'Kopie',
    'psrv.legal.sig.title':  'Unterschriftsbeglaubigung',
    'psrv.legal.sig.sub':    'Bestätigung der Echtheit einer Unterschrift',
    'psrv.legal.sig.li1':    'Zu beglaubigendes Originaldokument',
    'psrv.legal.sig.li2':    'Anwesenheit des Unterzeichners ist Pflicht',
    'psrv.legal.copy.title': 'Beglaubigte Kopie',
    'psrv.legal.copy.sub':   'Bestätigung, dass eine Kopie mit dem Original übereinstimmt',
    'psrv.legal.copy.li1':   'Zu zertifizierendes Originaldokument',
    'psrv.legal.copy.li3':   'Zu beglaubigende Fotokopie',
    'psrv.cert.h2':          'Bescheinigungen & Atteste',
    'psrv.cert.card.sub':    'Gebühren für konsularische Bescheinigungen und Atteste',
    'psrv.cert.li.celib':    'Ledigenzeugnis',
    'psrv.cert.li.res':      'Wohnsitzbescheinigung',
    'psrv.cert.li.cout':     'Brauchtumsbescheinigung',
    'psrv.cert.li.proc':     'Vollmacht',
    'psrv.faq.q1': 'Ist ein Termin zwingend erforderlich?',
    'psrv.faq.a1': 'Ja, die Terminvereinbarung ist für die Einreichung von Unterlagen obligatorisch. Es werden keine Unterlagen ohne vorherigen Termin angenommen. Termine können telefonisch oder per E-Mail vereinbart werden.',
    'psrv.faq.q2': 'Wie lange dauert die Bearbeitung eines Reisepasses?',
    'psrv.faq.a2': 'Die durchschnittliche Bearbeitungszeit für einen biometrischen Reisepass beträgt 4 bis 8 Wochen. Diese Frist hängt von den Bearbeitungsbedingungen in Abidjan ab. In nachgewiesenen Notfällen kann ein Notreisepass innerhalb von 24 bis 72 Stunden ausgestellt werden.',
    'psrv.faq.q3': 'Werden Gebühren bei Ablehnung erstattet?',
    'psrv.faq.a3': 'Nein, die Konsulargebühren sind nicht erstattungsfähig, auch nicht bei Ablehnung des Antrags. Es ist daher wichtig sicherzustellen, dass Ihre Unterlagen vollständig sind, bevor Sie sie einreichen.',
    'psrv.faq.q4': 'Kann ich meine Unterlagen per Post einsenden?',
    'psrv.faq.a4': 'Für bestimmte einfache Anträge (Beglaubigung von Kopien, bestimmte Bescheinigungen) ist die Einsendung per Einschreiben möglich. Für Reisepass- und Personalausweisanträge ist die persönliche Anwesenheit des Antragstellers zur biometrischen Erfassung zwingend erforderlich.',
    'psrv.faq.q5': 'Ich wohne in Ungarn — kann ich meine Angelegenheiten in Wien erledigen?',
    'psrv.faq.a5': 'Ja, die Botschaft der Elfenbeinküste in Wien ist für alle ivorischen Staatsangehörigen zuständig, die in Österreich, Ungarn, Slowenien, der Slowakei, Kroatien, Serbien, Rumänien und Bosnien-Herzegowina wohnen. Sie müssen für Ihre Angelegenheiten nach Wien kommen.',
    'pcon.h1':       'Kontakt & Öffnungszeiten',
    'pcon.desc':     'Vollständige Kontaktdaten und Öffnungszeiten. Alle Verfahren erfordern eine vorherige Terminvereinbarung.',
    'pcon.tel.lbl':  'Telefon',    'pcon.email.lbl':'Konsularische E-Mail',
    'pcon.addr.lbl': 'Adresse',   'pcon.urg.lbl':'Konsularische Notfälle',
    'pcon.urg.sub':  '24/7 für Notfälle verfügbar',
    'pcon.h.badge':  'Konsularische Öffnungszeiten', 'pcon.h.title':'Öffnungszeiten',
    'pcon.a.badge':  'Anfahrt',   'pcon.a.title':'So finden Sie uns',
    'pcon.f.badge':  'Schreiben Sie uns', 'pcon.f.title':'Kontaktformular',
    'pcon.f.desc':   'Füllen Sie dieses Formular aus. Wir antworten innerhalb von 3–5 Werktagen.',
    'pcon.f.send':   'Nachricht senden →',
    'pcon.urg2.title':'🚨 Konsularische Notfälle',
    'pcon.urg2.desc': 'Im Notfall außerhalb der Öffnungszeiten ist unser Bereitschaftsdienst 24/7 erreichbar.',
    'pcon.phone.hours':   'Mo – Fr : 09:30 – 16:00 Uhr',
    'pcon.email.reply':   'Antwort innerhalb von 1–2 Werktagen',
    'pcon.h.depot.title': 'Einreichung von Unterlagen',
    'pcon.h.depot.sub':   'Dokumente & Formulare',
    'pcon.h.days':        'Dienstag – Freitag',
    'pcon.h.closed':      'Montag · Samstag · Sonntag — <strong style="color:#e53e3e;">Geschlossen</strong>',
    'pcon.h.retrait.title':'Abholung von Unterlagen',
    'pcon.h.retrait.sub': 'Nur nach Terminvereinbarung',
    'pcon.h.feries':      'Einige Feiertage',
    'pcon.h.new-year':    'Neujahr',
    'pcon.h.labour':      'Tag der Arbeit (AT & CI)',
    'pcon.h.ci-national': 'Nationalfeiertag der Elfenbeinküste',
    'pcon.h.at-national': 'Österreichischer Nationalfeiertag',
    'pcon.h.xmas':        'Weihnachten',
    'pcon.a.metro':       '🚇 U-Bahn',
    'pcon.a.metro.desc':  'Linie <strong>U4</strong> — Station <strong>Heiligenstadt</strong>',
    'pcon.a.tram':        '🚋 Straßenbahn',
    'pcon.a.tram.desc':   'Linie <strong>D</strong> — Haltestelle <strong>Grinzinger Straße / Döblinger Hauptstraße</strong>',
    'pcon.a.bus':         '🚌 Bus',
    'pcon.a.bus.desc':    'Linie <strong>35A</strong> — Haltestelle <strong>Michael-Neumann-Gasse</strong>',
    'pcon.a.parking':     '🅿️ Parken',
    'pcon.a.parking.desc':'Parkmöglichkeiten in den umliegenden Straßen des 19. Bezirks.',
    'pcon.map.desc':      'Interaktive Karte — Botschaft der Elfenbeinküste in Wien',
    'pcon.map.btn':       'In Google Maps öffnen →',
    'pcon.f.before.title':'Vor der Kontaktaufnahme',
    'pcon.f.before.1':    'Prüfen Sie, ob Sie die Liste der erforderlichen Dokumente konsultiert haben',
    'pcon.f.before.2':    'Beschreiben Sie Ihr Anliegen klar und deutlich',
    'pcon.f.before.3':    'Geben Sie Ihr aktuelles Wohnsitzland an',
    'pcon.f.before.4':    'Rufen Sie im Notfall direkt die Notrufnummer an',
    'pcon.f.delays.title':'Antwortzeiten',
    'pcon.f.delay.email': 'E-Mail / Formular',
    'pcon.f.delay.email.val':'3–5 Werktage',
    'pcon.f.delay.rdv':   'Terminanfrage',
    'pcon.f.delay.rdv.val':'48 Werktunden',
    'pcon.f.delay.urg.val':'Sofort (Tel.)',
    'pcon.f.form.title':  'Senden Sie uns eine Nachricht',
    'pcon.f.prenom':      'Vorname',
    'pcon.f.nom':         'Nachname',
    'pcon.f.email':       'E-Mail-Adresse',
    'pcon.f.tel':         'Telefon',
    'pcon.f.pays':        'Wohnsitzland',
    'pcon.f.objet':       'Betreff der Anfrage',
    'pcon.f.message':     'Nachricht',
    'pcon.f.select.pays': '— Land auswählen —',
    'pcon.f.select.objet':'— Art der Anfrage auswählen —',
    'pcon.f.opt.rdv':     'Terminvereinbarung',
    'pcon.f.opt.passport':'Reisepass',
    'pcon.f.opt.visa':    'Visum',
    'pcon.f.opt.civil':   'Personenstand',
    'pcon.f.opt.legal':   'Beglaubigung von Dokumenten',
    'pcon.f.opt.cnie':    'Personalausweis',
    'pcon.f.opt.cert':    'Bescheinigung / Attest',
    'pcon.f.opt.urgent':  'Konsularischer Notfall',
    'pcon.f.opt.other':   'Sonstiges Anliegen',
    'pcon.f.rgpd':        'Ich stimme zu, dass meine Daten im Rahmen der Bearbeitung meines konsularischen Anliegens gemäß der DSGVO verwendet werden.',
    'pcon.urg2.label':    'Konsularische Notfälle',
    'pcon.urg2.avail':    '24/7 erreichbar',
    'pamb.h1':       'Botschaft der Elfenbeinküste',
    'pamb.desc':     "Offizielle Vertretung der Republik Côte d'Ivoire in Österreich, zuständig für 9 mitteleuropäische Länder.",
    'pamb.mis.badge':'Unsere Mission', 'pamb.mis.title':'Diplomatische & Konsularische Mission',
    'pamb.pays.badge':'Zuständigkeit', 'pamb.pays.title':'Zuständige Länder',
    'pamb.pays.sub': 'Die Botschaft ist für Staatsangehörige in den folgenden 9 Ländern zuständig.',
    'pamb.amb.badge':'Leitung',        'pamb.rel.badge':'Diplomatie',
    'pamb.rel.title':'Beziehungen Elfenbeinküste — Österreich',
    'pamb.ci.badge': 'Die Elfenbeinküste', 'pamb.ci.title':'Die Elfenbeinküste entdecken',
    'pamb.ci.p1':   "Die Republik Côte d'Ivoire ist ein westafrikanischer Staat, der im Süden an den Golf von Guinea grenzt. Als größte Volkswirtschaft der Westafrikanischen Wirtschafts- und Währungsunion (UEMOA) ist sie der weltgrößte Kakaoproduzent.",
    'pamb.ci.p2':   "Abidjan, die Wirtschaftshauptstadt, ist eine der dynamischsten Metropolen Subsahara-Afrikas. Yamoussoukro ist die politische und administrative Hauptstadt des Landes.",
    'pamb.ci.stat.area':'Fläche', 'pamb.ci.stat.pop':'Bevölkerung',
    'pamb.ci.stat.lang':'Amtssprache', 'pamb.ci.stat.lang.val':'Französisch',
    'pamb.ci.stat.currency':'Währung', 'pamb.ci.stat.indep':'Unabhängigkeit',
    'pamb.ci.stat.indep.val':'7. August 1960', 'pamb.ci.stat.capital':'Hauptstadt',
    'pamb.ci.republic':"Republik Côte d'Ivoire",
    'pamb.mis.p1':   'Die Botschaft der Republik Côte d\'Ivoire in Österreich ist die offizielle diplomatische Vertretung der Elfenbeinküste in Wien. Sie verteidigt die ivorischen Interessen, fördert bilaterale Beziehungen und schützt ihre Staatsangehörigen.',
    'pamb.mis.p2':   'Gegründet gemäß dem Wiener Übereinkommen über diplomatische Beziehungen von 1961, erfüllt die Botschaft eine doppelte Mission: diplomatisch (Vertretung des Staates beim Gastland) und konsular (Unterstützung ivorischer Staatsangehöriger in der Jurisdiktion).',
    'pamb.mis.p3':   'Im Rahmen ihrer territorialen Zuständigkeit deckt die Botschaft 9 Länder ab: Österreich, Ungarn, Slowenien, Slowakei, Kroatien, Serbien, Rumänien und Bosnien-Herzegowina.',
    'pamb.stat.countries':'Länder im diplomatischen Amtsbereich', 'pamb.stat.conv':'Wiener Konvention', 'pamb.stat.ci':'Elfenbeinküste', 'pamb.stat.host':'Gastgeberland',
    'pamb.amb.title':"Außerordentlicher und bevollmächtigter Botschafter der Republik Côte d'Ivoire in Österreich",
    'pamb.amb.p1':   'Seine Exzellenz Herr Cissé Yacouba ist bei der Republik Österreich als Außerordentlicher und Bevollmächtigter Botschafter der Republik Côte d\'Ivoire akkreditiert. Er ist auch bei Ungarn, Slowenien, der Slowakei, Kroatien, Serbien, Rumänien und Bosnien-Herzegowina akkreditiert.',
    'pamb.amb.p2':   'Mit einer langen diplomatischen Karriere im Dienst der Elfenbeinküste vertritt Seine Exzellenz Herr Cissé Yacouba die Interessen der Ivorischen Republik, fördert bilaterale und multilaterale Beziehungen und koordiniert alle Dienste der Botschaft.',
    'pcon.addr.official':'📍 Geografische Adresse',
    'pcon.table.window':'Konsularsschalter',
    'srv.badge.passport':'Reisedokument','srv.badge.visa':'Einreisevisum','srv.badge.identity':'Personalausweis',
  },

  /* ==================== ENGLISH ==================== */
  en: {
    'topbar.address':'Michael-Neumann-Gasse 2 - 3rd Floor, 1190 Vienna',
    'topbar.hours':  'Mon–Fri : 9:30 AM – 4:00 PM',
    'nav.home':      'Home',
    'nav.embassy':   'The Embassy',
    'nav.services':  'Consular Services',
    'nav.contact':   'Contact & Hours',
    'alert.text':    'An appointment is required for all consular procedures.',
    'alert.link':    'Book an appointment →',
    'hero.eyebrow':  'Consular Service',
    'hero.h1':       "Welcome to the Embassy of<br><em>Côte d'Ivoire</em> in Austria",
    'hero.desc':     "We assist Ivorian nationals residing in Central Europe with all their administrative and consular procedures from Vienna.",
    'hero.btn1':     'Our Consular Services',
    'hero.btn2':     'Book an Appointment',
    'hero.card.title':'Practical Information',
    'hero.addr.lbl': 'Address',
    'hero.hours.lbl':'General Embassy Hours',
    'hero.hours.val':'Mon – Fri : 9:30 AM – 4:00 PM',
    'hero.tel.lbl':  'Phone',
    'hero.jurid.lbl':'Consular Jurisdiction',
    'hero.jurid.val':'9 Central European countries',
    'srv.badge':     'Our Services',
    'srv.title':     'Available Consular Services',
    'srv.subtitle':  "All our services are available to Ivorian nationals and foreign citizens wishing to visit Côte d'Ivoire.",
    'srv.passport':  'Passport',
    'srv.passport.d':"First application, renewal and emergency passport for Ivorian nationals.",
    'srv.visa':      'Entry Visa',
    'srv.visa.d':    "Tourist, business and transit visas for foreign nationals wishing to enter Côte d'Ivoire.",
    'srv.civil':     'Civil Registry',
    'srv.civil.d':   'Birth, marriage and death certificates, transcriptions and civil status documents.',
    'srv.legal':     'Legalisation',
    'srv.legal.d':   'Legalisation and apostille of official documents, signature authentication.',
    'srv.cnie':      'National ID Card',
    'srv.cnie.d':    'Electronic national identity card for Ivorian nationals in Central Europe.',
    'srv.cert':      'Certificates & Attestations',
    'srv.cert.d':    'Life, residence and nationality certificates and official attestations.',
    'srv.more':      'Learn more',
    'home.hours.badge': 'Embassy Hours',
    'info.badge':    'Consular Hours',
    'info.title':    'Opening Hours',
    'info.subtitle': 'The consular service receives visitors by appointment only.',
    'info.rdv':      'Book an appointment →',
    'info.ct.title': 'Contact Us',
    'info.ct.sub':   'For any question or consular emergency',
    'info.addr.lbl': 'Address',    'info.tel.lbl':'Phone',
    'info.email.lbl':'Consular Email', 'info.urg.lbl':'Emergency (out of hours)',
    'info.metro.lbl':'Getting here',
    'pays.badge':    'Constituency',
    'pays.title':    'Diplomatic Constituency',
    'pays.subtitle': "The Embassy of Côte d'Ivoire in Vienna has consular jurisdiction over 9 Central European and Balkan countries.",
    'actu.badge':    'News',
    'actu.title':    'Information & Announcements',
    'actu.all':      'All news →',
    'cta.title':     'Need consular assistance?',
    'cta.desc':      'Our team is available to assist you with all your administrative procedures. Book an appointment online or contact us directly.',
    'cta.btn1':      'Book an Appointment', 'cta.btn2':'View Services',
    'footer.desc':   "Embassy of the Republic of Côte d'Ivoire in Austria, serving 9 Central European countries. Official consular service.",
    'footer.srv':    'Services', 'footer.info':'Information', 'footer.contact':'Contact',
    'footer.nav':    'Navigation',
    'footer.nav.ambassador': 'The Ambassador',
    'footer.nav.circonscrip': 'Diplomatic Constituency',
    'footer.nav.contact': 'Contact',
    'footer.srv.passport': 'Passport',
    'footer.srv.visa':     'Visa',
    'footer.srv.civil':    'Civil Registry',
    'footer.srv.legal':    'Legalisation',
    'footer.srv.cert':     'Certificates',
    'footer.legal':  'Legal Notice', 'footer.privacy':'Privacy Policy',
    'footer.access': 'Accessibility', 'footer.sitemap':'Sitemap',
    'footer.copy':   '© 2025 Embassy of the Republic of Côte d\'Ivoire in Austria. All rights reserved.',
    'footer.link.amb':'→ The Ambassador',
    'logo.name':     "Embassy of Côte d'Ivoire",
    'logo.subtitle': 'Republic of Côte d\'Ivoire — Vienna, Austria',
    'skip.link':     'Skip to main content',
    'alert.important':'Important notice:',
    'table.day':'Day','table.hours':'Hours',
    'day.mon':'Monday','day.tue':'Tuesday','day.wed':'Wednesday','day.thu':'Thursday',
    'day.fri':'Friday','day.sat':'Saturday','day.sun':'Sunday','day.closed':'Closed',
    'hours.val':'9:30 AM – 4:00 PM',
    'info.note':'Closed on Austrian and Ivorian public holidays.',
    'month.jan':'Jan','month.feb':'Feb','month.mar':'Mar','month.apr':'Apr',
    'month.may':'May','month.jun':'Jun','month.jul':'Jul','month.aug':'Aug',
    'month.sep':'Sep','month.oct':'Oct','month.nov':'Nov','month.dec':'Dec',
    'addr.street':'Michael-Neumann-Gasse 2 - 3rd Floor', 'pays.at':'Austria','pays.at.cap':'Vienna (seat)',
    'pays.hu':'Hungary','pays.si':'Slovenia','pays.sk':'Slovakia',
    'pays.hr':'Croatia','pays.rs':'Serbia','pays.ro':'Romania','pays.ba':'Bosnia-Herzegovina','pays.md':'Moldova',
    'actu.tag.event':'Event','actu.tag.info':'Information','actu.tag.mission':'Economic Mission',
    'actu.ev1.title':"Economic Mission: Visit by the President of the Economic, Social, Environmental and Cultural Council",
    'actu.ev1.desc': "The Embassy of Côte d'Ivoire in Vienna welcomed the President of the Economic, Social, Environmental and Cultural Council as part of an economic mission to strengthen ties between Côte d'Ivoire and Central Europe.",
    'actu.ev1.date': '2 June 2025',
    'actu.n1.title': 'New passport application form',
    'actu.n1.desc':  'Update of the biometric passport application form.',
    'actu.n2.title': 'Exceptional closure — Labour Day',
    'actu.n2.desc':  'The consular service will be closed on 1 May 2025 for Labour Day.',
    'actu.n3.title': 'Regularisation campaign for nationals',
    'actu.n3.desc':  'The Embassy is organising a day dedicated to the regularisation of documents.',
    'actu.n4.title': 'Change in visa processing times',
    'actu.n4.desc':  'Visa processing times are now 5 to 10 working days.',
    'psrv.h1':       'Consular Services',
    'psrv.desc':     "Find all administrative procedures offered by the Embassy of Côte d'Ivoire in Vienna.",
    'psrv.appt':     'Appointment Required', 'psrv.appt.d':'No procedure without a prior appointment',
    'psrv.delay':    'Processing Times',     'psrv.delay.d':'Variable depending on the file',
    'psrv.pay':      'Online payments only', 'psrv.pay.d':'All consular fees must be paid online prior to your appointment',
    'psrv.docs':     'Complete File Required','psrv.docs.d':'Bring all necessary documents',
    'psrv.faq.badge':'FAQ', 'psrv.faq.title':'Frequently Asked Questions',
    'psrv.cta.title':'Ready to start your procedure?',
    'psrv.cta.desc': 'Contact us to make an appointment or get additional information about your file.',
    'psrv.cta.btn1': 'Book an Appointment', 'psrv.cta.btn2':'📞 Call Now',
    /* Services — detailed content */
    'nav.annonces':          'Information & Announcements',
    'psrv.pass.h2':          'Biometric Passport',
    'psrv.docs.label':       'Required documents:',
    'psrv.fees.consular':    'Consular fees',
    'psrv.fees.visa':        'Visa fees',
    'psrv.fees.generic':     'Fees',
    'psrv.li.form':          'Completed and signed application form',
    'psrv.pass.li.birth3':   'Original birth certificate (less than 3 months old)',
    'psrv.pass.li.birth':    'Original birth certificate',
    'psrv.pass.li.nat':      'Ivorian nationality certificate',
    'psrv.pass.li.nat.cert': 'Nationality certificate',
    'psrv.pass.li.cni.casier':'Valid national ID card or criminal record extract',
    'psrv.pass.li.cni':      'Valid national ID card',
    'psrv.pass.li.photos':   '2 colour passport photos (white background, 35×45mm)',
    'psrv.pass.li.photos.rec':'2 recent passport photos',
    'psrv.pass.li.resid':    'Proof of residence (less than 3 months old)',
    'psrv.pass.li.old':      'Previous passport original (even if expired)',
    'psrv.pass.new.title':   'First Application',
    'psrv.pass.new.sub':     'For persons who have never had a passport',
    'psrv.pass.new.delay':   'Processing time: 4 to 8 weeks depending on processing in Abidjan',
    'psrv.pass.renew.title': 'Renewal',
    'psrv.pass.renew.sub':   'Expired or soon-to-expire passport',
    'psrv.pass.renew.delay': 'Processing time: 4 to 8 weeks',
    'psrv.pass.urg.title':   'Emergency Passport',
    'psrv.pass.urg.sub':     'In case of loss, theft or proven emergency',
    'psrv.pass.urg.li1':     'Loss/theft report (Austrian police)',
    'psrv.pass.urg.li5':     'Proof of urgency (flight ticket, etc.)',
    'psrv.pass.urg.delay':   'Processing time: 24 to 72 hours depending on situation',
    'psrv.visa.h2':          "Visa for Côte d'Ivoire",
    'psrv.visa.li.pass6m':   'Valid passport (min. 6 months beyond the stay)',
    'psrv.visa.li.pass6':    'Valid passport (min. 6 months)',
    'psrv.visa.li.pass':     'Valid passport',
    'psrv.visa.li.form':     'Completed visa application form',
    'psrv.visa.li.lodging':  "Proof of accommodation in Côte d'Ivoire",
    'psrv.visa.li.ticket':   'Return flight ticket',
    'psrv.visa.li.ticket.rt':'Return flight ticket',
    'psrv.visa.li.bank':     'Bank statements (last 3 months)',
    'psrv.visa.li.insurance':'Valid travel insurance',
    'psrv.visa.li.insur':    'Travel insurance',
    'psrv.visa.li.invite':   'Invitation letter from an Ivorian company',
    'psrv.visa.li.kbis':     'Company registration extract',
    'psrv.visa.tour.title':  'Tourist Visa',
    'psrv.visa.tour.sub':    'Stay of up to 90 days',
    'psrv.visa.biz.title':   'Business Visa',
    'psrv.visa.biz.sub':     'Professional and commercial activities',
    'psrv.visa.trans.title': 'Transit Visa',
    'psrv.visa.trans.sub':   'Stopover in Ivorian territory',
    'psrv.visa.trans.li2':   "Flight ticket with stopover in Côte d'Ivoire",
    'psrv.visa.trans.li3':   'Visa for final destination country',
    'psrv.visa.trans.li4':   'Completed transit application form',
    'psrv.visa.delay10':     'Processing time: 5 to 10 business days',
    'psrv.visa.delay5':      'Processing time: 3 to 5 business days',
    'psrv.civil.h2':         'Civil Registry Documents',
    'psrv.civil.card.title': 'Available documents',
    'psrv.civil.card.sub':   'Fees for consular civil registry documents',
    'psrv.civil.li.deces':   'Death certificate',
    'psrv.civil.li.mariage': 'Marriage certificate',
    'psrv.civil.li.admin':   'Administrative attestation',
    'psrv.civil.li.renon':   'Declaration of renunciation of nationality',
    'psrv.civil.li.cic':     'Consular identity card',
    'psrv.civil.li.celeb':   'Marriage ceremony',
    'psrv.civil.li.vie':     'Life certificate',
    'psrv.civil.li.naiss':   'Birth extract',
    'psrv.civil.li.lp':      'Laissez-passer for voluntary departure',
    'psrv.civil.li.legal.adm':'Legalisation of administrative documents',
    'psrv.civil.li.legal.ent':'Legalisation of corporate documents',
    'psrv.civil.li.trans':   'Transcription of civil status records',
    'psrv.civil.docs.title': '📋 Common required documents',
    'psrv.civil.docs.li1':   'Valid photo ID (national ID card or passport)',
    'psrv.civil.docs.li2':   'Proof of family relationship or civil status (depending on document)',
    'psrv.civil.docs.li3':   'Original documents to be transcribed/corrected',
    'psrv.civil.note':       'Note:',
    'psrv.civil.note.text':  'Documents issued abroad require a certified translation into French by a sworn translator.',
    'psrv.legal.h2':         'Document Legalisation',
    'psrv.legal.sub':        'Legalisation is the act by which the Embassy certifies the authenticity of an official document.',
    'psrv.legal.ivo.title':  'Ivorian documents',
    'psrv.legal.ivo.sub':    'Legalisation for use in Europe',
    'psrv.legal.ivo.li1':    'Original Ivorian document with official signature',
    'psrv.legal.li.id':      "Applicant's photo ID",
    'psrv.legal.li.form':    'Completed legalisation form',
    'psrv.legal.li.id.valid':'Valid photo ID',
    'psrv.legal.per.doc':    'document',
    'psrv.legal.per.sig':    'signature',
    'psrv.legal.per.copy':   'copy',
    'psrv.legal.sig.title':  'Signature Authentication',
    'psrv.legal.sig.sub':    'Certification of the authenticity of a signature',
    'psrv.legal.sig.li1':    'Original document to be authenticated',
    'psrv.legal.sig.li2':    'Mandatory presence of the signatory',
    'psrv.legal.copy.title': 'Certified True Copy',
    'psrv.legal.copy.sub':   'Certification that a copy is consistent with the original',
    'psrv.legal.copy.li1':   'Original document to be certified',
    'psrv.legal.copy.li3':   'Photocopy to be certified',
    'psrv.cert.h2':          'Certificates & Attestations',
    'psrv.cert.card.sub':    'Fees for consular certificates and attestations',
    'psrv.cert.li.celib':    'Single status certificate',
    'psrv.cert.li.res':      'Residence certificate',
    'psrv.cert.li.cout':     'Customary law certificate',
    'psrv.cert.li.proc':     'Power of attorney',
    'psrv.faq.q1': 'Is an appointment absolutely required?',
    'psrv.faq.a1': 'Yes, booking an appointment is mandatory for all file submissions. No file will be accepted without a prior appointment. You can book by phone or email.',
    'psrv.faq.q2': 'How long does passport processing take?',
    'psrv.faq.a2': 'The average processing time for a biometric passport is 4 to 8 weeks. This depends on processing conditions in Abidjan. In duly justified emergencies, an emergency passport can be issued within 24 to 72 hours.',
    'psrv.faq.q3': 'Are fees refundable in case of refusal?',
    'psrv.faq.a3': 'No, consular fees are non-refundable, including in cases of application refusal. It is therefore important to ensure your file is complete before submitting it.',
    'psrv.faq.q4': 'Can I send my file by post?',
    'psrv.faq.a4': 'For certain simple requests (legalisation of copies, some certificates), sending by registered post is possible. For passport and national ID card applications, the physical presence of the applicant is mandatory for biometric data capture.',
    'psrv.faq.q5': 'I live in Hungary — can I handle my affairs in Vienna?',
    'psrv.faq.a5': "Yes, the Embassy of Côte d'Ivoire in Vienna is competent for all Ivorian nationals residing in Austria, Hungary, Slovenia, Slovakia, Croatia, Serbia, Romania and Bosnia-Herzegovina. You must travel to Vienna to carry out your procedures.",
    'pcon.h1':       'Contact & Hours',
    'pcon.desc':     'Full contact details and opening hours. All procedures require a prior appointment.',
    'pcon.tel.lbl':  'Phone',     'pcon.email.lbl':'Consular Email',
    'pcon.addr.lbl': 'Address',   'pcon.urg.lbl':'Consular Emergencies',
    'pcon.urg.sub':  'Available 24/7 for emergencies',
    'pcon.h.badge':  'Consular Hours',     'pcon.h.title':'Opening Hours',
    'pcon.a.badge':  'Getting Here','pcon.a.title':'How to Find Us',
    'pcon.f.badge':  'Write to Us','pcon.f.title':'Contact Form',
    'pcon.f.desc':   'Fill in this form. We will reply within 3–5 business days.',
    'pcon.f.send':   'Send Message →',
    'pcon.urg2.title':'🚨 Consular Emergencies',
    'pcon.urg2.desc': 'In case of emergency outside opening hours, our duty service is available 24/7.',
    'pcon.phone.hours':   'Mon – Fri : 9:30 AM – 4:00 PM',
    'pcon.email.reply':   'Reply within 1–2 business days',
    'pcon.h.depot.title': 'File Submission',
    'pcon.h.depot.sub':   'Documents & forms',
    'pcon.h.days':        'Tuesday – Friday',
    'pcon.h.closed':      'Monday · Saturday · Sunday — <strong style="color:#e53e3e;">Closed</strong>',
    'pcon.h.retrait.title':'File Collection',
    'pcon.h.retrait.sub': 'By appointment only',
    'pcon.h.feries':      'Key public holidays',
    'pcon.h.new-year':    "New Year's Day",
    'pcon.h.labour':      'Labour Day (AT & CI)',
    'pcon.h.ci-national': "Côte d'Ivoire National Day",
    'pcon.h.at-national': 'Austrian National Day',
    'pcon.h.xmas':        'Christmas',
    'pcon.a.metro':       '🚇 Underground (U-Bahn)',
    'pcon.a.metro.desc':  'Line <strong>U4</strong> — Station <strong>Heiligenstadt</strong>',
    'pcon.a.tram':        '🚋 Tram (Straßenbahn)',
    'pcon.a.tram.desc':   'Line <strong>D</strong> — Stop <strong>Grinzinger Straße / Döblinger Hauptstraße</strong>',
    'pcon.a.bus':         '🚌 Bus',
    'pcon.a.bus.desc':    'Line <strong>35A</strong> — Stop <strong>Michael-Neumann-Gasse</strong>',
    'pcon.a.parking':     '🅿️ Parking',
    'pcon.a.parking.desc':'Street parking is available in the surrounding streets of the 19th district.',
    'pcon.map.desc':      "Interactive map — Embassy of Côte d'Ivoire in Vienna",
    'pcon.map.btn':       'Open in Google Maps →',
    'pcon.f.before.title':'Before contacting us',
    'pcon.f.before.1':    'Check that you have consulted the list of required documents',
    'pcon.f.before.2':    'Clearly state the nature of your request',
    'pcon.f.before.3':    'Indicate your current country of residence',
    'pcon.f.before.4':    'For emergencies, call the emergency number directly',
    'pcon.f.delays.title':'Response times',
    'pcon.f.delay.email': 'Email / form',
    'pcon.f.delay.email.val':'3–5 business days',
    'pcon.f.delay.rdv':   'Appointment request',
    'pcon.f.delay.rdv.val':'48 working hours',
    'pcon.f.delay.urg.val':'Immediate (tel.)',
    'pcon.f.form.title':  'Send us a message',
    'pcon.f.prenom':      'First name',
    'pcon.f.nom':         'Last name',
    'pcon.f.email':       'Email address',
    'pcon.f.tel':         'Phone',
    'pcon.f.pays':        'Country of residence',
    'pcon.f.objet':       'Subject of request',
    'pcon.f.message':     'Message',
    'pcon.f.select.pays': '— Select a country —',
    'pcon.f.select.objet':'— Select a type of request —',
    'pcon.f.opt.rdv':     'Appointment booking',
    'pcon.f.opt.passport':'Passport',
    'pcon.f.opt.visa':    'Visa',
    'pcon.f.opt.civil':   'Civil registry',
    'pcon.f.opt.legal':   'Document legalisation',
    'pcon.f.opt.cnie':    'National ID Card',
    'pcon.f.opt.cert':    'Certificate / Attestation',
    'pcon.f.opt.urgent':  'Consular emergency',
    'pcon.f.opt.other':   'Other request',
    'pcon.f.rgpd':        'I agree that my data may be used for the processing of my consular request, in accordance with GDPR.',
    'pcon.urg2.label':    'Consular Emergencies',
    'pcon.urg2.avail':    'Available 24/7',
    'pamb.h1':       "Embassy of Côte d'Ivoire",
    'pamb.desc':     "Official representation of the Republic of Côte d'Ivoire in Austria, serving 9 Central European countries.",
    'pamb.mis.badge':'Our Mission', 'pamb.mis.title':'Diplomatic & Consular Mission',
    'pamb.pays.badge':'Jurisdiction','pamb.pays.title':'Countries Served',
    'pamb.pays.sub': 'The Embassy of Côte d\'Ivoire in Vienna is competent for nationals in the following 9 countries.',
    'pamb.amb.badge':'Leadership',  'pamb.rel.badge':'Diplomacy',
    'pamb.rel.title':"Relations Côte d'Ivoire — Austria",
    'pamb.ci.badge': "Côte d'Ivoire",'pamb.ci.title':"Discover Côte d'Ivoire",
    'pamb.ci.p1':   "The Republic of Côte d'Ivoire is a West African country bordered to the south by the Gulf of Guinea. The largest economy in the West African Economic and Monetary Union (UEMOA), it is the world's leading cocoa producer.",
    'pamb.ci.p2':   "Abidjan, the economic capital, is one of the most dynamic metropolises in sub-Saharan Africa. Yamoussoukro is the political and administrative capital of the country.",
    'pamb.ci.stat.area':'Area', 'pamb.ci.stat.pop':'Population',
    'pamb.ci.stat.lang':'Official language', 'pamb.ci.stat.lang.val':'French',
    'pamb.ci.stat.currency':'Currency', 'pamb.ci.stat.indep':'Independence',
    'pamb.ci.stat.indep.val':'August 7, 1960', 'pamb.ci.stat.capital':'Capital',
    'pamb.ci.republic':"Republic of Côte d'Ivoire",
    'pamb.mis.p1':   "The Embassy of the Republic of Côte d'Ivoire in Austria is the official diplomatic representation of Côte d'Ivoire in Vienna. It defends Ivorian interests, develops bilateral relations and protects its nationals.",
    'pamb.mis.p2':   "Established in accordance with the Vienna Convention on Diplomatic Relations of 1961, the Embassy fulfils a dual mission: diplomatic (representing the State to the host country) and consular (assisting Ivorian nationals residing in its jurisdiction).",
    'pamb.mis.p3':   "Within its territorial jurisdiction, the Embassy covers 9 countries: Austria, Hungary, Slovenia, Slovakia, Croatia, Serbia, Romania and Bosnia-Herzegovina.",
    'pamb.stat.countries':'countries in the Diplomatic Constituency', 'pamb.stat.conv':'Vienna Convention', 'pamb.stat.ci':"Côte d'Ivoire", 'pamb.stat.host':'Host country',
    'pamb.amb.title':"Ambassador Extraordinary and Plenipotentiary of the Republic of Côte d'Ivoire in Austria",
    'pamb.amb.p1':   "His Excellency Mr Cissé Yacouba is accredited to the Republic of Austria as Ambassador Extraordinary and Plenipotentiary of the Republic of Côte d'Ivoire. He is also accredited to Hungary, Slovenia, Slovakia, Croatia, Serbia, Romania and Bosnia-Herzegovina.",
    'pamb.amb.p2':   "With a long diplomatic career in the service of Côte d'Ivoire, His Excellency Mr Cissé Yacouba represents the interests of the Ivorian Republic, promotes bilateral and multilateral relations, and coordinates all the services of the Embassy.",
    'pcon.addr.official':'📍 Geographic Address',
    'pcon.table.window':'Consular window',
    'srv.badge.passport':'Travel document','srv.badge.visa':'Entry Visa','srv.badge.identity':'ID Card',
    /* Page Annonces */
    'ann.h1':              'Information & Announcements',
    'ann.desc':            'Find here all official information, important notices and announcements from the Embassy of Côte d\'Ivoire in Vienna.',
    'ann.pinned.label':    'Pinned — Urgent',
    'ann.pinned.title':    'Exceptional Closure — National Day of Côte d\'Ivoire',
    'ann.pinned.desc':     'The Embassy of Côte d\'Ivoire in Vienna will be <strong>closed on Friday, August 7, 2026</strong> on the occasion of the National Day of the Republic of Côte d\'Ivoire (66th anniversary of independence). Services will resume normally on Monday, August 10, 2026 at 09:30.',
    'ann.pinned.date':     'Published on May 25, 2026',
    'ann.filter.all':      'All',
    'ann.filter.urgent':   'Urgent',
    'ann.filter.admin':    'Administrative',
    'ann.filter.event':    'Events',
    'ann.filter.communique':'Communiqués',
    'ann.cat.mission':     'Economic mission',
    'ann.cat.diplo':       'Diplomacy',
    'ann.cat.actu':        'News',
    'ann.cat.communique':  'Communiqué',
    'ann.btn.read':        ' Read article',
    'ann.btn.readfull':    ' Read full communiqué',
    'ann.empty':           'No announcements in this category at the moment.',
    'ann.sidebar.links':   'Useful links',
    'ann.sidebar.passport':'Passport renewal',
    'ann.sidebar.visa':    'Visa application',
    'ann.sidebar.civil':   'Civil registration',
    'ann.sidebar.rdv':     'Book an appointment',
    'ann.sidebar.hours':   'Opening hours',
    'ann.sidebar.contact': 'Direct contact',
    'ann.sub.title':       'Receive announcements',
    'ann.sub.desc':        'Sign up to be notified of new announcements and important information.',
    'ann.sub.btn':         'Subscribe to alerts',
    /* Article titles & descriptions */
    'ann.a1.title': 'Economic mission: Aka Aouélé leads a delegation of the Economic, Social, Environmental and Cultural Council (CESEC) to Austria',
    'ann.a1.desc':  "The President of the CESEC, Aka Aouélé, led an Ivorian delegation to Austria to strengthen exchanges and cooperation between Côte d'Ivoire and its European partners.",
    'ann.a2.title': "Ivorian diplomacy honoured in Vienna: Côte d'Ivoire assumes the presidency of the Comprehensive Nuclear-Test-Ban Treaty Organisation (CTBTO)",
    'ann.a2.desc':  "Côte d'Ivoire assumed the presidency of the Preparatory Commission of the Comprehensive Nuclear-Test-Ban Treaty Organisation (CTBTO), marking a major milestone for Ivorian diplomacy on the international stage in Vienna.",
    'ann.a3.title': "Civil nuclear energy: Côte d'Ivoire advocates for stronger support from the International Atomic Energy Agency (IAEA)",
    'ann.a3.desc':  "Côte d'Ivoire expressed in Vienna, during the IAEA proceedings, its desire to benefit from enhanced support for the development of its civil nuclear programme.",
    'ann.a4.title': 'Ivorian diplomacy in Austria: Ambassador Cissé Yacouba meets with the Governor of Vorarlberg',
    'ann.a4.desc':  "His Excellency Mr Cissé Yacouba, Ambassador of Côte d'Ivoire to Austria, met with the Governor of the State of Vorarlberg as part of efforts to strengthen bilateral relations between Côte d'Ivoire and Austria.",
    'ann.a5.title': 'Official communiqué — Presentation of letters of credence',
    'ann.a5.desc':  "His Excellency Mr Cissé Yacouba, Ambassador Extraordinary and Plenipotentiary of the Republic of Côte d'Ivoire, presented his letters of credence to the Federal President of the Republic of Austria at an official ceremony at the Hofburg Palace in Vienna.",
  }
};

/* ============================================================
   setLang — applique la langue choisie
   ============================================================ */
function setLang(lang) {
  if (!translations[lang]) return;

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (translations[lang][key] !== undefined) el.textContent = translations[lang][key];
  });

  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.dataset.i18nHtml;
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });

  document.documentElement.lang = lang === 'de' ? 'de' : lang === 'en' ? 'en' : 'fr';
  localStorage.setItem('ambaci-lang', lang);
}

(function initLang() {
  const saved = localStorage.getItem('ambaci-lang') || 'fr';
  setLang(saved);
})();

/* ============================================================
   Navigation mobile — hamburger menu
   ============================================================ */
const menuToggle = document.getElementById('menu-toggle');
const mainNav    = document.getElementById('main-nav');

if (menuToggle && mainNav) {
  menuToggle.addEventListener('click', () => {
    const isOpen = mainNav.classList.toggle('is-open');
    menuToggle.setAttribute('aria-expanded', String(isOpen));
    document.body.style.overflow = isOpen ? 'hidden' : '';
  });

  document.addEventListener('click', (e) => {
    if (!mainNav.contains(e.target) && !menuToggle.contains(e.target)) {
      mainNav.classList.remove('is-open');
      menuToggle.setAttribute('aria-expanded', 'false');
      document.body.style.overflow = '';
    }
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && mainNav.classList.contains('is-open')) {
      mainNav.classList.remove('is-open');
      menuToggle.setAttribute('aria-expanded', 'false');
      document.body.style.overflow = '';
      menuToggle.focus();
    }
  });
}

/* ============================================================
   Alerte — fermeture
   ============================================================ */
const alertClose  = document.getElementById('alert-close');
const alertBanner = document.getElementById('alert-banner');

if (alertClose && alertBanner) {
  alertClose.addEventListener('click', () => {
    alertBanner.style.maxHeight = alertBanner.scrollHeight + 'px';
    requestAnimationFrame(() => {
      alertBanner.style.transition = 'max-height 0.3s ease, opacity 0.3s ease';
      alertBanner.style.maxHeight  = '0';
      alertBanner.style.opacity    = '0';
      alertBanner.style.overflow   = 'hidden';
    });
    setTimeout(() => alertBanner.remove(), 350);
  });
}

/* ============================================================
   Accordion (FAQ)
   ============================================================ */
document.querySelectorAll('.accordion-trigger').forEach((trigger) => {
  trigger.addEventListener('click', () => {
    const panelId = trigger.getAttribute('aria-controls');
    const panel   = document.getElementById(panelId);
    if (!panel) return;
    const isExpanded = trigger.getAttribute('aria-expanded') === 'true';
    document.querySelectorAll('.accordion-trigger').forEach((t) => {
      if (t !== trigger) {
        t.setAttribute('aria-expanded', 'false');
        const p = document.getElementById(t.getAttribute('aria-controls'));
        if (p) p.classList.remove('is-open');
      }
    });
    trigger.setAttribute('aria-expanded', String(!isExpanded));
    panel.classList.toggle('is-open', !isExpanded);
  });
});

/* ============================================================
   Surlignage du jour courant
   ============================================================ */
(function highlightToday() {
  const days = ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
  const todayName = days[new Date().getDay()];
  document.querySelectorAll('.horaires-table tbody tr').forEach((row) => {
    const cell = row.querySelector('td:first-child');
    if (cell && cell.textContent.trim() === todayName) row.classList.add('today-row');
  });
})();

/* ============================================================
   Formulaire de contact
   ============================================================ */
const contactForm = document.getElementById('contact-form');
if (contactForm) {
  contactForm.addEventListener('submit', (e) => {
    e.preventDefault();
    const required = contactForm.querySelectorAll('[required]');
    let valid = true;
    required.forEach((field) => {
      const ok = field.type === 'checkbox' ? field.checked : field.value.trim() !== '';
      if (!ok) { valid = false; field.style.borderColor = '#DC2626'; field.setAttribute('aria-invalid','true'); }
      else { field.style.borderColor = ''; field.removeAttribute('aria-invalid'); }
    });
    if (!valid) { const f = contactForm.querySelector('[aria-invalid="true"]'); if (f) f.focus(); return; }
    const btn = contactForm.querySelector('[type="submit"]');
    const orig = btn.textContent;
    btn.disabled = true; btn.textContent = 'Envoi en cours…';
    setTimeout(() => {
      btn.textContent = '✓ Message envoyé !'; btn.style.background = 'var(--green)'; contactForm.reset();
      setTimeout(() => { btn.disabled = false; btn.textContent = orig; btn.style.background = ''; }, 4000);
    }, 1500);
  });
  contactForm.querySelectorAll('[required]').forEach((field) => {
    field.addEventListener('input', () => { field.style.borderColor = ''; field.removeAttribute('aria-invalid'); });
  });
}

/* ============================================================
   Sticky header
   ============================================================ */
(function stickyHeader() {
  const header = document.querySelector('.site-header');
  if (!header) return;
  window.addEventListener('scroll', () => {
    header.style.boxShadow = window.scrollY > 80 ? 'var(--shadow-md)' : 'var(--shadow-sm)';
  }, { passive: true });
})();

/* ============================================================
   Smooth scroll
   ============================================================ */
document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
  anchor.addEventListener('click', (e) => {
    const id = anchor.getAttribute('href').slice(1);
    const target = document.getElementById(id);
    if (target) {
      e.preventDefault();
      const headerH = document.querySelector('.site-header')?.offsetHeight ?? 80;
      window.scrollTo({ top: target.getBoundingClientRect().top + window.scrollY - headerH - 16, behavior: 'smooth' });
    }
  });
});

