'use strict';

/* ============================================================
   TRADUCTIONS FR / DE / EN — Version complète
   ============================================================ */
const T = {
  fr: {
    /* ── Navigation & chrome ── */
    'nav.home':'Accueil','nav.embassy':'Ambassade','nav.services':'Services',
    'nav.annonces':'Annonces','nav.contact':'Contact',
    'logo.name':"Ambassade de Côte d'Ivoire",
    'logo.sub':'Vienne, Autriche',
    'footer.copy':"© 2025 Ambassade de la République de Côte d'Ivoire en Autriche",
    'footer.links.home':'Accueil','footer.links.embassy':'Ambassade',
    'footer.links.services':'Services','footer.links.annonces':'Annonces',
    'footer.links.contact':'Contact',

    /* ── Top bar ── */
    'topbar.address':'Michael-Neumann-Gasse 2 - 3ème Etage, 1190 Wien',
    'topbar.hours':'Lun–Ven : 09h30 – 16h00',

    /* ── Alert ── */
    'alert.text':'RDV obligatoire pour toute démarche.',
    'alert.link':'Prendre RDV →',

    /* ── Hero (index) ── */
    'hero.tag':'Service Consulaire',
    'hero.h1':"Bienvenue à l'Ambassade de<br><em>Côte d'Ivoire</em>",
    'hero.desc':"Vos démarches consulaires depuis Vienne, pour 9 pays d'Europe centrale.",
    'hero.btn1':'Nos services','hero.btn2':'Prendre RDV',
    'hero.countries':'9 pays desservis',
    'hero.floor':'1190 Wien, 3ème Etage',

    /* ── Index — Services grid ── */
    'badge.services':'Nos services',
    'srv.title':'Services consulaires','srv.more':'Voir →',
    'srv.passport':'Passeport','srv.passport.sub':'Demande & renouvellement',
    'srv.visa':'Visa','srv.visa.sub':'Touristique, affaires, transit',
    'srv.civil':'État civil','srv.civil.sub':'Actes & transcriptions',
    'srv.legal':'Légalisation','srv.legal.sub':'Documents officiels',
    'srv.cert':'Certificats','srv.cert.sub':'Vie, résidence, nationalité',
    'srv.wa':'WhatsApp','srv.wa.sub':'Contact direct',

    /* ── Index — Infos pratiques ── */
    'badge.contact':'Contact',
    'info.practical':'Informations pratiques',
    'info.contact.title':'Nous contacter',
    'info.address.label':'Adresse géographique',
    'info.phone.label':'Téléphone',
    'info.email.label':'Email',
    'info.emergency.label':'Urgences 24h/24',

    /* ── Index — Pays ── */
    'badge.jurisdiction':'Juridiction',
    'pays.title':'Circonscription diplomatique',
    'pays.sub':"9 pays d'Europe centrale et des Balkans",
    'pays.at':'Autriche','pays.hu':'Hongrie','pays.si':'Slovénie',
    'pays.sk':'Slovaquie','pays.hr':'Croatie','pays.rs':'Serbie',
    'pays.ro':'Roumanie','pays.ba':'Bosnie',

    /* ── Index — Actualités ── */
    'badge.news':'Actualités',
    'actu.title':'Informations & Annonces',
    'actu.tag1':'Mission économique',
    'actu.h3':"Visite du Président du Conseil Économique, Social, Environnemental et Culturel",
    'actu.p1':"Mission économique visant à renforcer les liens entre la Côte d'Ivoire et l'Europe centrale.",
    'actu.date1':'02 juin 2025',
    'actu.month1':'Mai',
    'news1.title':'Nouveau formulaire de demande de passeport',
    'news1.desc':'Mise à jour du formulaire biométrique.',
    'news2.title':'Fermeture — Fête du Travail',
    'news2.desc':'Fermé le 1er mai 2025.',

    /* ── CTA ── */
    'cta.title':"Besoin d'aide consulaire ?",
    'cta.desc':'Dépôt de dossiers et retraits du mardi au vendredi — sur rendez-vous.',
    'cta.btn':'Prendre rendez-vous',
    'cta.call':'+43 1 581007610',

    /* ── Services page ── */
    'srv.breadcrumb':'Services',
    'srv.page.h1':'Services consulaires',
    'srv.page.sub':'Toutes vos démarches administratives officielles',
    'info.rdv':'RDV obligatoire','info.rdv.sub':'Aucune démarche sans RDV',
    'info.payment':'Paiement en ligne','info.payment.sub':'Uniquement en ligne',
    'info.delay':'Délais variables','info.delay.sub':'Selon la démarche',
    'info.file':'Dossier complet','info.file.sub':'Tous documents requis',
    'badge.passport':'Document de voyage',
    'srv.passport.title':'Passeport biométrique',
    'srv.pp.new':'Première demande','srv.pp.new.sub':'Pour les personnes sans passeport',
    'srv.pp.renew':'Renouvellement','srv.pp.renew.sub':'Passeport expiré ou à renouveler',
    'srv.pp.urgent':'Passeport d\'urgence','srv.pp.urgent.sub':'Perte, vol ou urgence',
    'srv.fees':'Frais consulaires',
    'srv.delay.std':'Délai : 4 à 8 semaines',
    'srv.delay.urgent':'Délai : 24 à 72h',
    /* Première demande */
    'pp.new.req1':"Acte de naissance original (moins de 3 mois)",
    'pp.new.req2':"Certificat de nationalité ivoirienne",
    'pp.new.req3':"2 photos d'identité (fond blanc, 35×45mm)",
    'pp.new.req4':"Justificatif de résidence",
    /* Renouvellement */
    'pp.renew.req1':"Ancien passeport original",
    'pp.renew.req2':"Acte de naissance (moins de 3 mois)",
    'pp.renew.req3':"2 photos d'identité récentes",
    /* Urgence */
    'pp.urgent.req1':"Déclaration de perte/vol (police)",
    'pp.urgent.req2':"Acte de naissance original",
    'pp.urgent.req3':"Justification de l'urgence",
    /* Visa touristique */
    'visa.tourist.req1':"Passeport valide (min. 6 mois)",
    'visa.tourist.req2':"Billet aller-retour",
    'visa.tourist.req3':"Justificatif d'hébergement",
    'visa.tourist.req4':"Assurance voyage",
    /* Visa affaires */
    'visa.business.req1':"Passeport valide",
    'visa.business.req2':"Lettre d'invitation d'une entreprise CI",
    'visa.business.req3':"Extrait Kbis",
    'badge.visa':'Visa d\'entrée',
    'srv.visa.title':'Visa pour la Côte d\'Ivoire',
    'srv.visa.tourist':'Visa touristique','srv.visa.tourist.sub':'Séjour jusqu\'à 90 jours',
    'srv.visa.business':'Visa d\'affaires','srv.visa.business.sub':'Activités professionnelles',
    'srv.visa.fees':'Frais de visa',
    'srv.delay.visa':'Délai : 5 à 10 jours ouvrés',
    'badge.civil':'État civil',
    'srv.civil.title':'Actes d\'état civil',
    'srv.civil.online':'Actes disponibles','srv.civil.online.sub':'Cliquez pour payer en ligne',
    'civil.act.death':'Acte de décès',
    'civil.act.marriage':'Acte de mariage',
    'civil.act.admin':'Attestation Administrative',
    'civil.act.id':'Carte d\'identité consulaire',
    'civil.act.wed':'Célébration de mariage',
    'civil.act.life':'Certificat de vie',
    'civil.act.birth':'Extrait de naissance',
    'civil.act.pass':'Laissez-passer volontaire',
    'civil.act.legal.admin':'Légalisation documents admin.',
    'civil.act.legal.co':'Légalisation pour Entreprises',
    'civil.act.transcription':'Transcription actes d\'État Civil',
    'badge.cert':'Certificats',
    'srv.cert.title':'Certificats & Attestations',
    'srv.cert.online':'Certificats consulaires','srv.cert.online.sub':'Paiement en ligne',
    'cert.life':'Certificat de vie',
    'cert.single':'Certificat de célibat',
    'cert.residence':'Certificat de résidence',
    'cert.nationality':'Certificat de nationalité',
    'cert.custom':'Certificat de coutume',
    'cert.proxy':'Procuration',
    'badge.faq':'FAQ',
    'srv.faq.title':'Questions fréquentes',
    'faq1.q':'Faut-il un rendez-vous ?',
    'faq1.a':'Oui, la prise de rendez-vous est obligatoire pour tout dépôt de dossier. Contactez-nous par téléphone ou email.',
    'faq2.q':'Délai passeport ?',
    'faq2.a':'4 à 8 semaines en général. En urgence : 24 à 72 heures selon situation.',
    'faq3.q':'Je réside en Hongrie, puis-je venir à Vienne ?',
    'faq3.a':"Oui. L'Ambassade couvre 9 pays : Autriche, Hongrie, Slovénie, Slovaquie, Croatie, Serbie, Roumanie et Bosnie-Herzégovine.",
    'srv.cta.title':'Prêt à commencer ?',
    'srv.cta.desc':'Prenez rendez-vous ou payez vos frais consulaires en ligne.',
    'btn.rdv':'Prendre rendez-vous','btn.call':'Appeler',

    /* ── Ambassade page ── */
    'amb.breadcrumb':'Ambassade',
    'amb.h1':"L'Ambassade de Côte d'Ivoire",
    'amb.sub':'Représentation officielle en Autriche depuis Vienne',
    'amb.stat.countries':'pays dans la circonscription',
    'amb.stat.conv':'Conv. de Vienne',
    'amb.stat.ci':"Côte d'Ivoire",
    'amb.stat.host':'Pays hôte',
    'badge.mission':'Notre mission',
    'amb.mission.title':'Mission diplomatique & consulaire',
    'amb.mission.p1':"L'Ambassade de la République de Côte d'Ivoire en Autriche est la représentation diplomatique officielle de la Côte d'Ivoire à Vienne. Elle assure la défense des intérêts ivoiriens, le développement des relations bilatérales et la protection de ses ressortissants.",
    'amb.mission.p2':"Établie conformément à la Convention de Vienne de 1961, l'Ambassade remplit une double mission : diplomatique et consulaire.",
    'badge.direction':'Direction',
    'amb.title':"Ambassadeur Extraordinaire et Plénipotentiaire de la République de Côte d'Ivoire en Autriche",
    'amb.p1':"Son Excellence Monsieur Cissé Yacouba est accrédité auprès de la République d'Autriche depuis 2023. Il est également accrédité auprès de la Hongrie, la Slovénie, la Slovaquie, la Croatie, la Serbie, la Roumanie et la Bosnie-Herzégovine.",
    'amb.p2':"Fort d'une longue carrière diplomatique, Son Excellence représente les intérêts de la République ivoirienne et coordonne l'ensemble des services de l'Ambassade.",
    'badge.diplomacy':'Diplomatie',
    'amb.rel.title':'Relations CI — Autriche',
    'rel.bilateral.title':'Coopération bilatérale',
    'rel.bilateral.desc':'Relations fondées sur le respect mutuel, la coopération économique, culturelle et éducative.',
    'rel.trade.title':'Échanges commerciaux',
    'rel.trade.desc':"La CI exporte cacao, café et matières premières. L'Autriche est partenaire dans l'industrie et les services.",
    'rel.academic.title':'Coopération académique',
    'rel.academic.desc':'Échanges universitaires et programmes de bourses pour étudiants ivoiriens.',
    'rel.intl.title':'Organisations internationales',
    'rel.intl.desc':"Vienne abrite ONUDI, AIEA, ONUDC. L'Ambassade coordonne la participation ivoirienne.",
    'badge.ci':"La Côte d'Ivoire",
    'ci.title':"Découvrir la Côte d'Ivoire",
    'ci.area':'Superficie','ci.pop':'Population',
    'ci.indep':'Indépendance','ci.capital':'Capitale',
    'amb.cta.title':'Besoin d\'un service ?',
    'amb.cta.desc':'Notre équipe est disponible du lundi au vendredi.',
    'amb.cta.btn1':'Voir les services','amb.cta.btn2':'Nous contacter',

    /* ── Contact page ── */
    'contact.breadcrumb':'Contact',
    'contact.h1':'Contact & Horaires',
    'contact.sub':'Coordonnées et horaires du service consulaire',
    'contact.phone.label':'Téléphone','contact.email.label':'Email',
    'contact.address.label':'Adresse','contact.emergency.label':'Urgences',
    'contact.address.val':'1190 Wien, 3ème Etage',
    'badge.hours':'Horaires consulaires',
    'contact.hours.title':'Heures d\'ouverture',
    'contact.hours.sub':'Sur rendez-vous uniquement',
    'table.day':'Jour','table.counter':'Guichet',
    'contact.holidays':'Quelques jours fériés',
    'holiday.newyear':'Nouvel An','holiday.labor':'Fête du Travail',
    'holiday.ci':'Fête Nationale CI','holiday.at':'Fête Nationale AT',
    'badge.access':'Accès',
    'contact.addr.title':'Adresse géographique',
    'contact.floor':'3ème Etage — 1190 Wien, Autriche',
    'contact.metro':'Métro','contact.metro.val':'U4 — Station Heiligenstadt',
    'contact.bus':'Bus','contact.bus.val':'Ligne 35A — Arrêt Michael-Neumann-Gasse',
    'contact.maps':'Ouvrir dans Google Maps →',
    'badge.form':'Nous écrire',
    'contact.form.title':'Formulaire de contact',
    'form.firstname':'Prénom','form.lastname':'Nom','form.email':'Email',
    'form.phone':'Téléphone','form.country':'Pays de résidence',
    'form.country.select':'— Sélectionner —',
    'form.subject':'Objet','form.subject.select':'— Type de demande —',
    'form.rdv':'Prise de rendez-vous','form.passport':'Passeport','form.visa':'Visa',
    'form.civil':'État civil','form.emergency':'Urgence consulaire',
    'form.message':'Message','form.placeholder':'Décrivez votre demande...',
    'form.submit':'Envoyer →',
    'contact.urgency.title':'Urgences consulaires',
    'contact.urgency.text':'En cas d\'urgence hors horaires (perte de passeport, décès, hospitalisation, arrestation), notre permanence est disponible 24h/24.',

    /* ── Annonces page ── */
    'annonces.breadcrumb':'Annonces',
    'annonces.h1':'Informations & Annonces',
    'annonces.sub':'Avis officiels, fermetures, événements et communiqués',
    'annonces.pinned':'Épinglé — Urgent',
    'annonces.pin.title':'Fermeture — Fête Nationale de Côte d\'Ivoire',
    'annonces.pin.text':"L'Ambassade sera <strong>fermée le lundi 7 août 2025</strong> pour la Fête Nationale (65ème anniversaire). Reprise le mardi 8 août à 09h30.",
    'annonces.pin.date':'Publié le 10 juillet 2025',
    'filter.all':'Toutes','filter.urgent':'Urgentes',
    'filter.admin':'Administratif','filter.event':'Événements',
    'filter.communique':'Communiqués',
    /* Catégories */
    'cat.urgent':'Urgent','cat.admin':'Administratif',
    'cat.event':'Événement','cat.communique':'Communiqué',
    /* Annonce 1 */
    'ann1.date':'15 juillet 2025',
    'ann1.title':'Perturbation — Travaux de rénovation',
    'ann1.text':'Services perturbés du <strong>21 au 25 juillet</strong>. Dépôts de dossiers sur RDV uniquement.',
    'btn.rdv.short':'Prendre RDV','btn.write':'Écrire',
    /* Annonce 2 */
    'ann2.date':'1er juillet 2025',
    'ann2.title':'Nouveaux tarifs consulaires — 1er août 2025',
    'ann2.text':'Le nouveau barème des prestations consulaires entre en vigueur le <strong>1er août 2025</strong>.',
    'btn.download':'Télécharger PDF','btn.services':'Services',
    /* Annonce 3 */
    'ann3.date':'20 juin 2025',
    'ann3.title':'Journée Consulaire Itinérante — Budapest, 12 sept.',
    'ann3.text':'Démarches administratives sur place à Budapest. Inscription avant le <strong>29 août 2025</strong>.',
    'btn.register':'S\'inscrire','btn.programme':'Programme',
    /* Annonce 4 */
    'ann4.date':'5 juin 2025',
    'ann4.title':'Rappel — Documents requis pour le passeport',
    'ann4.text':'Ancien passeport, acte de naissance légalisé, 2 photos, justificatif de domicile. Tout dossier incomplet sera retourné.',
    'btn.procedure':'Procédure complète',
    /* Annonce 5 */
    'ann5.date':'15 mai 2025',
    'ann5.title':'Présentation de lettres de créance',
    'ann5.text':'S.E.M. Cissé Yacouba a présenté ses lettres de créance au Président fédéral d\'Autriche au Palais de la Hofburg.',
    'btn.read':'Lire le communiqué',
    'annonce.subscribe.title':'Recevez les annonces',
    'annonce.subscribe.desc':'Inscrivez-vous pour être notifié des nouvelles informations importantes.',
    'annonce.subscribe.placeholder':'votre@email.com',
    'annonce.subscribe.btn':'OK →',
    'annonce.follow':'Suivez-nous',
    'annonce.empty':'Aucune annonce dans cette catégorie.',

    /* ── Days ── */
    'day.mon':'Lundi','day.tue':'Mardi','day.wed':'Mercredi','day.thu':'Jeudi',
    'day.fri':'Vendredi','day.sat':'Samedi','day.sun':'Dimanche','day.closed':'Fermé',
    'hours.val':'09h30 – 16h00',
    'hours.depot':'Dépôt de dossiers',
    'hours.retrait':'Retraits de dossiers',
    'hours.rdv':'(sur rendez-vous)',
    'hours.days':'Mardi – Vendredi',
    'hours.depot.time':'09:00 – 14:00',
    'hours.retrait.time':'14:00 – 16:00',
    'hours.closed.days':'Lundi · Sam. · Dim.',

    /* ── Découvrir l'Autriche ── */
    'nav.discover':'Découvrir',
    'pdec.badge':'Guide pratique','pdec.h1':"Découvrir l'Autriche",
    'pdec.desc':"Que vous soyez de passage pour quelques jours ou installé durablement en Autriche, ce guide pratique vous accompagne pour ne manquer de rien à Vienne : transports, hébergement, restauration, visites et informations utiles.",
    'pdec.toc.airport':'Aéroport','pdec.toc.mobility':'Transports','pdec.toc.hotels':'Hébergement',
    'pdec.toc.food':'Restauration','pdec.toc.sights':'Visites','pdec.toc.practical':'Infos pratiques',
    'pdec.airport.badge':'Arrivée à Vienne','pdec.airport.title':"Arrivée à l'aéroport de Vienne-Schwechat (VIE)",
    'pdec.airport.intro':"L'aéroport de Vienne-Schwechat se situe à environ 18 à 20 km du centre-ville, soit 20 à 30 minutes de trajet selon l'option choisie.",
    'pdec.airport.taxi.title':'Taxi / Transfert privé',
    'pdec.airport.taxi.desc':"File de taxis officiels devant les arrivées (plaques se terminant par « TX », signe lumineux sur le toit).",
    'pdec.airport.taxi.li1':'Taxi 40100 — forfait aéroport ~42 € (précisez « course aéroport » à la réservation)',
    'pdec.airport.taxi.li2':"Taxi 31300 — forfait ~37 € via l'application",
    'pdec.airport.taxi.li3':'Apps VTC : Bolt, Uber, FREE NOW (~19 à 57 €)',
    'pdec.airport.taxi.price':'~35 à 50 € au compteur','pdec.airport.taxi.for':'Idéal avec bagages ou en groupe',
    'pdec.airport.cat.title':'City Airport Train (CAT)',
    'pdec.airport.cat.desc':"Train direct sans arrêt entre l'aéroport et Wien Mitte.",
    'pdec.airport.cat.price':'16 min — ~11 à 14,90 €','pdec.airport.cat.for':'Idéal pour un trajet rapide et confortable',
    'pdec.airport.train.title':'Train S7 (ÖBB)',
    'pdec.airport.train.desc':"Train régional reliant l'aéroport au centre-ville, avec plusieurs arrêts.",
    'pdec.airport.train.price':'~25 min — ~4,50 €','pdec.airport.train.for':"L'option la plus économique",
    'pdec.airport.bus.title':'Bus Vienna Airport Lines',
    'pdec.airport.bus.desc':'Liaisons directes vers plusieurs points du centre-ville.',
    'pdec.airport.bus.price':'~20 à 30 min — ~8 à 10,50 €',"pdec.airport.bus.for":"Pratique si votre hôtel est proche d'un arrêt",
    'pdec.airport.tip.badge':'À savoir','pdec.airport.tip':"En cas d'arrivée après 23h, privilégiez un taxi : les transports en commun sont limités la nuit.",
    'pdec.price.lbl':'Tarif indicatif','pdec.for.lbl':'Pour qui',
    'pdec.mob.badge':'Se déplacer','pdec.mob.title':'Se déplacer dans Vienne',
    'pdec.mob.tickets.title':'Acheter son ticket',
    'pdec.mob.tickets.desc':"Les tickets s'achètent en ligne sur le WienMobil Ticketshop ou aux distributeurs dans les stations (sélectionnez l'anglais pour plus de facilité).",
    'pdec.mob.table.ticket':'Ticket','pdec.mob.table.price':'Tarif (2026)',
    'pdec.mob.table.single':'Trajet simple (Einzelfahrt)','pdec.mob.table.single.val':'3,20 € papier / 3,00 € appli',
    'pdec.mob.table.day':'Pass 24h','pdec.mob.table.day.val':'10,20 €',
    'pdec.mob.table.week':'Ticket numérique 7 jours','pdec.mob.table.week.val':'25,20 €',
    'pdec.mob.table.citycard':'Vienna City Card (24h)','pdec.mob.table.citycard.val':'à partir de ~19 €',
    'pdec.mob.rule.badge':"Règle d'or",
    'pdec.mob.rule.text':"Validez votre ticket papier dans les boîtiers bleus avant de monter à bord — les tickets numériques (appli/en ligne) sont automatiquement validés. Amende en cas de contrôle sans ticket valide : 135 €.",
    'pdec.mob.airport.note':"⚠️ L'aéroport est hors de la zone centrale (Zone 100) : un ticket de ville ne suffit pas, il faut un supplément zone extérieure (~2,20 €) ou un ticket spécifique aéroport.",
    'pdec.mob.app.badge':'Application recommandée','pdec.mob.app.title':"Téléchargez l'application WienMobil",
    'pdec.mob.app.desc':"L'application officielle des Wiener Linien permet d'acheter vos tickets (moins chers qu'en papier), de planifier vos trajets en temps réel et de réserver les vélos en libre-service.",
    'pdec.mob.app.appstore':'App Store','pdec.mob.app.googleplay':'Google Play',
    'pdec.mob.other.title':'Autres mobilités',
    'pdec.mob.other.li1':"Vélos en libre-service WienMobil Rad, réservables via l'application",
    'pdec.mob.other.li2':'Réseau dense : 5 lignes de métro (U-Bahn), tramways, bus et S-Bahn',
    'pdec.mob.other.li3':'Bus de nuit le week-end pour rentrer en toute sécurité',
    'pdec.fees.note':'Tarifs indicatifs (2026) — vérifiez les tarifs à jour sur',
    'pdec.hotels.badge':'Se loger','pdec.hotels.title':'Où séjourner à Vienne',
    'pdec.hotels.desc':"Une sélection indicative d'hébergements répartis par budget, pour préparer votre séjour à Vienne.",
    'pdec.hotels.budget.title':'Économique / Auberges','pdec.hotels.mid.title':'Milieu / Supérieur','pdec.hotels.top.title':'Haut de gamme',
    'pdec.hotels.more':"Voir plus d'hôtels à Vienne →",
    'pdec.disclaimer':"Les établissements et services cités sont fournis à titre informatif. L'Ambassade ne recommande ni ne garantit aucun prestataire privé. Tarifs indicatifs susceptibles de modification.",
    'pdec.food.badge':'Se restaurer','pdec.food.title':'Manger à Vienne',
    'pdec.food.delivery.title':'Commander en ligne','pdec.food.delivery.desc':'Plusieurs plateformes de livraison de repas sont disponibles à Vienne :',
    'pdec.food.african.title':'Cuisine africaine & ouest-africaine',
    'pdec.food.african.desc':'Pour retrouver les saveurs du pays — jollof rice, mafé, poulet braisé, attiéké :',
    'pdec.food.viennese.title':'Spécialités viennoises à goûter',
    'pdec.food.viennese.desc':'Wiener Schnitzel, Sachertorte, Apfelstrudel — et faites un tour au marché du Naschmarkt pour découvrir les saveurs locales.',
    'pdec.sights.badge':'Visiter','pdec.sights.title':'Lieux Incontournables de Vienne',
    'pdec.sights.desc':'Quelques sites emblématiques à découvrir lors de votre séjour.',
    'pdec.sights.schoenbrunn.title':'Château de Schönbrunn','pdec.sights.schoenbrunn.desc':"Ancienne résidence d'été impériale et ses jardins classés à l'UNESCO.",
    'pdec.sights.hofburg.title':'Palais de la Hofburg','pdec.sights.hofburg.desc':'Ancien siège du pouvoir des Habsbourg, en plein cœur de Vienne.',
    'pdec.sights.stephansdom.title':'Cathédrale Saint-Étienne','pdec.sights.stephansdom.desc':'Symbole emblématique de Vienne, avec sa flèche gothique et sa tour panoramique.',
    'pdec.sights.belvedere.title':'Palais & Musée du Belvédère','pdec.sights.belvedere.desc':'« Le Baiser » de Gustav Klimt et de superbes jardins à la française.',
    'pdec.sights.prater.title':'Le Prater','pdec.sights.prater.desc':"Célèbre parc d'attractions et sa grande roue historique, le Riesenrad.",
    'pdec.sights.ring.title':'Ringstrasse','pdec.sights.ring.desc':"Le grand boulevard circulaire desservant l'Opéra, le Parlement et l'Hôtel de Ville.",
    'pdec.sights.museumsquartier.title':'MuseumsQuartier','pdec.sights.museumsquartier.desc':"Un des plus grands quartiers culturels du monde : musées et lieux de vie.",
    'pdec.sights.more':'Office de tourisme officiel — vienna.info →',
    'pdec.practical.badge':'Pour ne rien oublier','pdec.practical.title':'Informations pratiques',
    'pdec.practical.emergency.title':"Numéros d'urgence",
    'pdec.practical.emergency.eu':'Urgence européenne','pdec.practical.emergency.police':'Police',
    'pdec.practical.emergency.fire':'Pompiers','pdec.practical.emergency.ambulance':'Ambulance',
    'pdec.practical.health.title':'Santé',
    'pdec.practical.health.desc':"Pharmacies (Apotheke, croix verte) ; la pharmacie de garde est affichée sur la porte de chaque officine fermée. Pensez à votre carte européenne d'assurance maladie ou à une assurance voyage.",
    'pdec.practical.money.title':'Argent','pdec.practical.money.desc':'Distributeurs (Bankomat) largement disponibles, paiement sans contact très répandu. Pourboire usuel : 5 à 10 %.',
    'pdec.practical.conn.title':'Connectivité','pdec.practical.conn.desc':'Cartes SIM locales disponibles auprès de A1, Magenta, Drei ou HoT. WiFi public dans de nombreux lieux publics.',
    'pdec.practical.weather.title':'Météo & quand venir','pdec.practical.weather.desc':"Le printemps et l'automne sont les saisons les plus agréables. L'hiver est froid (marchés de Noël), l'été chaud et ensoleillé.",
    'pdec.practical.german.title':"Quelques mots d'allemand utiles",
    'pdec.practical.german.li1':'Grüß Gott — Bonjour','pdec.practical.german.li2':'Danke — Merci',
    'pdec.practical.german.li3':"Bitte — S'il vous plaît / De rien",'pdec.practical.german.li4':'Entschuldigung — Pardon / Excusez-moi',
    'pdec.practical.german.li5':'Wie viel? — Combien ?',
    'pdec.practical.etiquette.title':'Étiquette & vie pratique',
    'pdec.practical.etiquette.desc':'La ponctualité est très appréciée. Les magasins sont généralement fermés le dimanche. Le tri des déchets est rigoureux et les transports en commun se vivent dans le calme.',
    'pdec.practical.excursions.title':'Excursions depuis Vienne',
    'pdec.practical.excursions.desc':'Bratislava (~1h), la vallée du Wachau, Salzbourg ou Graz sont facilement accessibles en train via les ÖBB.',
    'pdec.practical.diaspora.title':'Communauté ivoirienne & diaspora',
    'pdec.practical.diaspora.desc':"Contactez l'Ambassade ou suivez nos réseaux sociaux pour être informé des événements de la communauté ivoirienne en Autriche.",
    'pdec.cta.title':'Une question sur votre séjour ?',
    'pdec.cta.desc':"Notre équipe reste à votre disposition pour vous accompagner avant et pendant votre séjour en Autriche.",
    'pdec.cta.btn.whatsapp':'Contacter sur WhatsApp','pdec.cta.btn.contact':'Page Contact','pdec.cta.btn.rdv':'Prendre rendez-vous',
  },

  de: {
    /* ── Navigation & chrome ── */
    'nav.home':'Start','nav.embassy':'Botschaft','nav.services':'Dienste',
    'nav.annonces':'Ankündigungen','nav.contact':'Kontakt',
    'logo.name':'Botschaft der Elfenbeinküste',
    'logo.sub':'Wien, Österreich',
    'footer.copy':'© 2025 Botschaft der Republik Elfenbeinküste in Österreich',
    'footer.links.home':'Start','footer.links.embassy':'Botschaft',
    'footer.links.services':'Dienste','footer.links.annonces':'Ankündigungen',
    'footer.links.contact':'Kontakt',

    /* ── Top bar ── */
    'topbar.address':'Michael-Neumann-Gasse 2 - 3. Stock, 1190 Wien',
    'topbar.hours':'Mo–Fr : 09:30 – 16:00 Uhr',

    /* ── Alert ── */
    'alert.text':'Termin erforderlich für alle Verfahren.',
    'alert.link':'Termin buchen →',

    /* ── Hero ── */
    'hero.tag':'Konsulardienst',
    'hero.h1':'Willkommen bei der Botschaft der<br><em>Elfenbeinküste</em>',
    'hero.desc':'Ihre konsularischen Angelegenheiten von Wien aus, für 9 mitteleuropäische Länder.',
    'hero.btn1':'Unsere Dienste','hero.btn2':'Termin buchen',
    'hero.countries':'9 Länder betreut',
    'hero.floor':'1190 Wien, 3. Etage',

    /* ── Index — Services grid ── */
    'badge.services':'Unsere Dienste',
    'srv.title':'Konsularische Dienste','srv.more':'Mehr →',
    'srv.passport':'Reisepass','srv.passport.sub':'Antrag & Verlängerung',
    'srv.visa':'Visum','srv.visa.sub':'Tourismus, Geschäft, Transit',
    'srv.civil':'Standesamt','srv.civil.sub':'Urkunden & Transkriptionen',
    'srv.legal':'Beglaubigung','srv.legal.sub':'Offizielle Dokumente',
    'srv.cert':'Bescheinigungen','srv.cert.sub':'Leben, Wohnsitz, Staatsangehörigkeit',
    'srv.wa':'WhatsApp','srv.wa.sub':'Direktkontakt',

    /* ── Index — Infos pratiques ── */
    'badge.contact':'Kontakt',
    'info.practical':'Praktische Informationen',
    'info.contact.title':'Uns kontaktieren',
    'info.address.label':'Adresse',
    'info.phone.label':'Telefon',
    'info.email.label':'E-Mail',
    'info.emergency.label':'Notfall 24/7',

    /* ── Index — Pays ── */
    'badge.jurisdiction':'Zuständigkeit',
    'pays.title':'Diplomatischer Amtsbereich',
    'pays.sub':'9 Länder in Mitteleuropa und dem Balkan',
    'pays.at':'Österreich','pays.hu':'Ungarn','pays.si':'Slowenien',
    'pays.sk':'Slowakei','pays.hr':'Kroatien','pays.rs':'Serbien',
    'pays.ro':'Rumänien','pays.ba':'Bosnien',

    /* ── Index — Actualités ── */
    'badge.news':'Aktuelles',
    'actu.title':'Informationen & Ankündigungen',
    'actu.tag1':'Wirtschaftsmission',
    'actu.h3':'Besuch des Präsidenten des Wirtschafts-, Sozial-, Umwelt- und Kulturrats',
    'actu.p1':'Wirtschaftsmission zur Stärkung der Beziehungen zwischen der Elfenbeinküste und Mitteleuropa.',
    'actu.date1':'02. Juni 2025',
    'actu.month1':'Mai',
    'news1.title':'Neues Reisepassantragsformular',
    'news1.desc':'Aktualisierung des biometrischen Formulars.',
    'news2.title':'Schließung — Tag der Arbeit',
    'news2.desc':'Geschlossen am 1. Mai 2025.',

    /* ── CTA ── */
    'cta.title':'Konsularische Hilfe benötigt?',
    'cta.desc':'Einreichung und Abholung dienstags bis freitags — nach Terminvereinbarung.',
    'cta.btn':'Termin vereinbaren',
    'cta.call':'+43 1 581007610',

    /* ── Services page ── */
    'srv.breadcrumb':'Dienste',
    'srv.page.h1':'Konsularische Dienste',
    'srv.page.sub':'Alle Ihre offiziellen Verwaltungsangelegenheiten',
    'info.rdv':'Termin erforderlich','info.rdv.sub':'Keine Bearbeitung ohne Termin',
    'info.payment':'Online-Zahlung','info.payment.sub':'Ausschließlich online',
    'info.delay':'Variable Bearbeitungszeiten','info.delay.sub':'Je nach Verfahren',
    'info.file':'Vollständige Unterlagen','info.file.sub':'Alle Dokumente erforderlich',
    'badge.passport':'Reisedokument',
    'srv.passport.title':'Biometrischer Reisepass',
    'srv.pp.new':'Erstantrag','srv.pp.new.sub':'Für Personen ohne Reisepass',
    'srv.pp.renew':'Verlängerung','srv.pp.renew.sub':'Abgelaufener oder zu verlängernder Reisepass',
    'srv.pp.urgent':'Notreisepass','srv.pp.urgent.sub':'Verlust, Diebstahl oder Notfall',
    'srv.fees':'Konsulargebühren',
    'srv.delay.std':'Bearbeitungszeit: 4–8 Wochen',
    'srv.delay.urgent':'Bearbeitungszeit: 24–72 Std.',
    /* Première demande */
    'pp.new.req1':"Originale Geburtsurkunde (max. 3 Monate alt)",
    'pp.new.req2':"Bescheinigung der ivorischen Staatsangehörigkeit",
    'pp.new.req3':"2 Passfotos (weißer Hintergrund, 35×45mm)",
    'pp.new.req4':"Wohnsitznachweis",
    /* Renouvellement */
    'pp.renew.req1':"Originaler alter Reisepass",
    'pp.renew.req2':"Geburtsurkunde (max. 3 Monate alt)",
    'pp.renew.req3':"2 aktuelle Passfotos",
    /* Urgence */
    'pp.urgent.req1':"Verlust-/Diebstahlmeldung (Polizei)",
    'pp.urgent.req2':"Originale Geburtsurkunde",
    'pp.urgent.req3':"Nachweis der Dringlichkeit",
    /* Visa touristique */
    'visa.tourist.req1':"Gültiger Reisepass (mind. 6 Monate)",
    'visa.tourist.req2':"Hin- und Rückflugticket",
    'visa.tourist.req3':"Unterkunftsnachweis",
    'visa.tourist.req4':"Reiseversicherung",
    /* Visa affaires */
    'visa.business.req1':"Gültiger Reisepass",
    'visa.business.req2':"Einladungsschreiben eines ivorischen Unternehmens",
    'visa.business.req3':"Handelsregisterauszug",
    'badge.visa':'Einreisevisum',
    'srv.visa.title':'Visum für die Elfenbeinküste',
    'srv.visa.tourist':'Touristenvisum','srv.visa.tourist.sub':'Aufenthalt bis zu 90 Tagen',
    'srv.visa.business':'Geschäftsvisum','srv.visa.business.sub':'Berufliche Tätigkeiten',
    'srv.visa.fees':'Visumgebühren',
    'srv.delay.visa':'Bearbeitungszeit: 5–10 Werktage',
    'badge.civil':'Standesamt',
    'srv.civil.title':'Personenstandsurkunden',
    'srv.civil.online':'Verfügbare Urkunden','srv.civil.online.sub':'Klicken für Online-Zahlung',
    'civil.act.death':'Sterbeurkunde',
    'civil.act.marriage':'Heiratsurkunde',
    'civil.act.admin':'Verwaltungsbescheinigung',
    'civil.act.id':'Konsularischer Personalausweis',
    'civil.act.wed':'Eheschließung',
    'civil.act.life':'Lebensbescheinigung',
    'civil.act.birth':'Geburtsurkunde (Auszug)',
    'civil.act.pass':'Freiwilliger Reiseausweis',
    'civil.act.legal.admin':'Beglaubigung Verwaltungsdok.',
    'civil.act.legal.co':'Beglaubigung für Unternehmen',
    'civil.act.transcription':'Transkription Personenstandsurkunden',
    'badge.cert':'Bescheinigungen',
    'srv.cert.title':'Bescheinigungen & Nachweise',
    'srv.cert.online':'Konsularbescheinigungen','srv.cert.online.sub':'Online-Zahlung',
    'cert.life':'Lebensbescheinigung',
    'cert.single':'Ledigenzeugnis',
    'cert.residence':'Wohnsitzbescheinigung',
    'cert.nationality':'Staatsangehörigkeitsbescheinigung',
    'cert.custom':'Gewohnheitsrechtsbescheinigung',
    'cert.proxy':'Vollmacht',
    'badge.faq':'FAQ',
    'srv.faq.title':'Häufige Fragen',
    'faq1.q':'Ist ein Termin erforderlich?',
    'faq1.a':'Ja, ein Termin ist für alle Einreichungen erforderlich. Kontaktieren Sie uns telefonisch oder per E-Mail.',
    'faq2.q':'Wie lange dauert der Reisepass?',
    'faq2.a':'Im Allgemeinen 4 bis 8 Wochen. Im Notfall: 24 bis 72 Stunden.',
    'faq3.q':'Ich wohne in Ungarn, kann ich nach Wien kommen?',
    'faq3.a':'Ja. Die Botschaft ist für 9 Länder zuständig: Österreich, Ungarn, Slowenien, Slowakei, Kroatien, Serbien, Rumänien und Bosnien-Herzegowina.',
    'srv.cta.title':'Bereit anzufangen?',
    'srv.cta.desc':'Vereinbaren Sie einen Termin oder zahlen Sie Ihre Konsulargebühren online.',
    'btn.rdv':'Termin vereinbaren','btn.call':'Anrufen',

    /* ── Ambassade page ── */
    'amb.breadcrumb':'Botschaft',
    'amb.h1':'Die Botschaft der Elfenbeinküste',
    'amb.sub':'Offizielle Vertretung in Österreich von Wien aus',
    'amb.stat.countries':'Länder im Amtsbereich',
    'amb.stat.conv':'Wiener Konvention',
    'amb.stat.ci':'Elfenbeinküste',
    'amb.stat.host':'Gastland',
    'badge.mission':'Unsere Mission',
    'amb.mission.title':'Diplomatische & konsulare Mission',
    'amb.mission.p1':'Die Botschaft der Republik Côte d\'Ivoire in Österreich ist die offizielle diplomatische Vertretung der Elfenbeinküste in Wien. Sie verteidigt die ivorischen Interessen, fördert bilaterale Beziehungen und schützt ihre Staatsbürger.',
    'amb.mission.p2':'Gemäß der Wiener Konvention von 1961 erfüllt die Botschaft eine doppelte Aufgabe: diplomatisch und konsular.',
    'badge.direction':'Leitung',
    'amb.title':'Außerordentlicher und Bevollmächtigter Botschafter der Republik Elfenbeinküste in Österreich',
    'amb.p1':'Seine Exzellenz Herr Cissé Yacouba ist seit 2023 bei der Republik Österreich akkreditiert. Er ist auch in Ungarn, Slowenien, der Slowakei, Kroatien, Serbien, Rumänien und Bosnien-Herzegowina akkreditiert.',
    'amb.p2':'Mit einer langen diplomatischen Karriere vertritt Seine Exzellenz die Interessen der Republik Elfenbeinküste und koordiniert alle Dienste der Botschaft.',
    'badge.diplomacy':'Diplomatie',
    'amb.rel.title':'Beziehungen CI — Österreich',
    'rel.bilateral.title':'Bilaterale Zusammenarbeit',
    'rel.bilateral.desc':'Beziehungen auf Basis gegenseitigen Respekts, wirtschaftlicher, kultureller und bildungsbezogener Zusammenarbeit.',
    'rel.trade.title':'Handelsbeziehungen',
    'rel.trade.desc':'Die CI exportiert Kakao, Kaffee und Rohstoffe. Österreich ist Partner in Industrie und Dienstleistungen.',
    'rel.academic.title':'Akademische Zusammenarbeit',
    'rel.academic.desc':'Universitätsaustausch und Stipendienprogramme für ivorische Studenten.',
    'rel.intl.title':'Internationale Organisationen',
    'rel.intl.desc':'Wien beherbergt UNIDO, IAEA, UNODC. Die Botschaft koordiniert die ivorische Teilnahme.',
    'badge.ci':'Die Elfenbeinküste',
    'ci.title':'Die Elfenbeinküste entdecken',
    'ci.area':'Fläche','ci.pop':'Bevölkerung',
    'ci.indep':'Unabhängigkeit','ci.capital':'Hauptstadt',
    'amb.cta.title':'Brauchen Sie einen Dienst?',
    'amb.cta.desc':'Unser Team ist montags bis freitags verfügbar.',
    'amb.cta.btn1':'Dienste anzeigen','amb.cta.btn2':'Uns kontaktieren',

    /* ── Contact page ── */
    'contact.breadcrumb':'Kontakt',
    'contact.h1':'Kontakt & Öffnungszeiten',
    'contact.sub':'Kontaktdaten und Öffnungszeiten des Konsulardienstes',
    'contact.phone.label':'Telefon','contact.email.label':'E-Mail',
    'contact.address.label':'Adresse','contact.emergency.label':'Notfall',
    'contact.address.val':'1190 Wien, 3. Etage',
    'badge.hours':'Konsularische Öffnungszeiten',
    'contact.hours.title':'Öffnungszeiten',
    'contact.hours.sub':'Nur nach Terminvereinbarung',
    'table.day':'Tag','table.counter':'Schalter',
    'contact.holidays':'Feiertage (Auszug)',
    'holiday.newyear':'Neujahr','holiday.labor':'Tag der Arbeit',
    'holiday.ci':'Nationalfeiertag CI','holiday.at':'Nationalfeiertag AT',
    'badge.access':'Anfahrt',
    'contact.addr.title':'Adresse',
    'contact.floor':'3. Etage — 1190 Wien, Österreich',
    'contact.metro':'U-Bahn','contact.metro.val':'U4 — Haltestelle Heiligenstadt',
    'contact.bus':'Bus','contact.bus.val':'Linie 35A — Haltestelle Michael-Neumann-Gasse',
    'contact.maps':'In Google Maps öffnen →',
    'badge.form':'Nachricht schreiben',
    'contact.form.title':'Kontaktformular',
    'form.firstname':'Vorname','form.lastname':'Nachname','form.email':'E-Mail',
    'form.phone':'Telefon','form.country':'Wohnsitzland',
    'form.country.select':'— Auswählen —',
    'form.subject':'Betreff','form.subject.select':'— Art der Anfrage —',
    'form.rdv':'Terminvereinbarung','form.passport':'Reisepass','form.visa':'Visum',
    'form.civil':'Standesamt','form.emergency':'Konsularnotfall',
    'form.message':'Nachricht','form.placeholder':'Beschreiben Sie Ihr Anliegen...',
    'form.submit':'Absenden →',
    'contact.urgency.title':'Konsularische Notfälle',
    'contact.urgency.text':'Im Notfall außerhalb der Öffnungszeiten (Passverlust, Todesfall, Krankenhausaufenthalt, Verhaftung) ist unser Bereitschaftsdienst 24/7 erreichbar.',

    /* ── Annonces page ── */
    'annonces.breadcrumb':'Ankündigungen',
    'annonces.h1':'Informationen & Ankündigungen',
    'annonces.sub':'Offizielle Hinweise, Schließungen, Veranstaltungen und Mitteilungen',
    'annonces.pinned':'Angeheftet — Dringend',
    'annonces.pin.title':'Schließung — Nationalfeiertag der Elfenbeinküste',
    'annonces.pin.text':'Die Botschaft ist am <strong>Montag, 7. August 2025</strong> zum Nationalfeiertag geschlossen (65. Jahrestag). Wiederaufnahme am Dienstag, 8. August um 09:30 Uhr.',
    'annonces.pin.date':'Veröffentlicht am 10. Juli 2025',
    'filter.all':'Alle','filter.urgent':'Dringlich',
    'filter.admin':'Verwaltung','filter.event':'Veranstaltungen',
    'filter.communique':'Mitteilungen',
    /* Catégories */
    'cat.urgent':'Dringend','cat.admin':'Verwaltung',
    'cat.event':'Veranstaltung','cat.communique':'Mitteilung',
    /* Annonce 1 */
    'ann1.date':'15. Juli 2025',
    'ann1.title':'Störung — Renovierungsarbeiten',
    'ann1.text':'Dienste vom <strong>21. bis 25. Juli</strong> gestört. Einreichungen nur nach Terminvereinbarung.',
    'btn.rdv.short':'Termin buchen','btn.write':'Schreiben',
    /* Annonce 2 */
    'ann2.date':'1. Juli 2025',
    'ann2.title':'Neue Konsulargebühren — 1. August 2025',
    'ann2.text':'Der neue Gebührentarif tritt am <strong>1. August 2025</strong> in Kraft.',
    'btn.download':'PDF herunterladen','btn.services':'Dienste',
    /* Annonce 3 */
    'ann3.date':'20. Juni 2025',
    'ann3.title':'Konsulartag Budapest — 12. Sept.',
    'ann3.text':'Verwaltungsangelegenheiten vor Ort in Budapest. Anmeldung bis <strong>29. August 2025</strong>.',
    'btn.register':'Anmelden','btn.programme':'Programm',
    /* Annonce 4 */
    'ann4.date':'5. Juni 2025',
    'ann4.title':'Erinnerung — Erforderliche Dokumente für den Reisepass',
    'ann4.text':'Alter Reisepass, beglaubigte Geburtsurkunde, 2 Fotos, Wohnsitznachweis. Unvollständige Akten werden zurückgegeben.',
    'btn.procedure':'Vollständiges Verfahren',
    /* Annonce 5 */
    'ann5.date':'15. Mai 2025',
    'ann5.title':'Übergabe des Beglaubigungsschreibens',
    'ann5.text':'S.E. Herr Cissé Yacouba hat dem österreichischen Bundespräsidenten sein Beglaubigungsschreiben im Palais Hofburg überreicht.',
    'btn.read':'Mitteilung lesen',
    'annonce.subscribe.title':'Ankündigungen erhalten',
    'annonce.subscribe.desc':'Melden Sie sich an, um über neue wichtige Informationen benachrichtigt zu werden.',
    'annonce.subscribe.placeholder':'ihre@email.com',
    'annonce.subscribe.btn':'OK →',
    'annonce.follow':'Folgen Sie uns',
    'annonce.empty':'Keine Ankündigung in dieser Kategorie.',

    /* ── Days ── */
    'day.mon':'Montag','day.tue':'Dienstag','day.wed':'Mittwoch','day.thu':'Donnerstag',
    'day.fri':'Freitag','day.sat':'Samstag','day.sun':'Sonntag','day.closed':'Geschlossen',
    'hours.val':'09:30 – 16:00 Uhr',
    'hours.depot':'Akteneinsendung',
    'hours.retrait':'Aktenabholung',
    'hours.rdv':'(nach Terminvereinbarung)',
    'hours.days':'Dienstag – Freitag',
    'hours.depot.time':'09:00 – 14:00',
    'hours.retrait.time':'14:00 – 16:00',
    'hours.closed.days':'Mo. · Sa. · So.',

    /* ── Österreich entdecken ── */
    'nav.discover':'Entdecken',
    'pdec.badge':'Praktischer Leitfaden','pdec.h1':'Österreich entdecken',
    'pdec.desc':'Ob Sie nur für ein paar Tage zu Besuch sind oder dauerhaft in Österreich leben — dieser praktische Leitfaden begleitet Sie, damit Sie in Wien nichts verpassen: Verkehr, Unterkunft, Restaurants, Ausflüge und nützliche Informationen.',
    'pdec.toc.airport':'Flughafen','pdec.toc.mobility':'Verkehr','pdec.toc.hotels':'Unterkunft',
    'pdec.toc.food':'Essen','pdec.toc.sights':'Sehenswürdigkeiten','pdec.toc.practical':'Praktische Infos',
    'pdec.airport.badge':'Ankunft in Wien','pdec.airport.title':'Ankunft am Flughafen Wien-Schwechat (VIE)',
    'pdec.airport.intro':'Der Flughafen Wien-Schwechat liegt etwa 18 bis 20 km vom Stadtzentrum entfernt, das entspricht je nach gewählter Option 20 bis 30 Minuten Fahrzeit.',
    'pdec.airport.taxi.title':'Taxi / Privater Transfer',
    'pdec.airport.taxi.desc':'Offizielle Taxistände vor dem Ankunftsbereich (Kennzeichen mit „TX", Leuchtschild auf dem Dach).',
    'pdec.airport.taxi.li1':'Taxi 40100 — Flughafenpauschale ~42 € (bei der Buchung „Flughafenfahrt" angeben)',
    'pdec.airport.taxi.li2':'Taxi 31300 — Pauschale ~37 € über die App',
    'pdec.airport.taxi.li3':'Mitfahr-Apps: Bolt, Uber, FREE NOW (~19 bis 57 €)',
    'pdec.airport.taxi.price':'~35 bis 50 € laut Taxameter','pdec.airport.taxi.for':'Ideal mit Gepäck oder in der Gruppe',
    'pdec.airport.cat.title':'City Airport Train (CAT)',
    'pdec.airport.cat.desc':'Direktzug ohne Zwischenstopp zwischen dem Flughafen und Wien Mitte.',
    'pdec.airport.cat.price':'16 Min. — ~11 bis 14,90 €','pdec.airport.cat.for':'Ideal für eine schnelle und komfortable Verbindung',
    'pdec.airport.train.title':'Zug S7 (ÖBB)',
    'pdec.airport.train.desc':'Regionalzug zwischen Flughafen und Stadtzentrum mit mehreren Halten.',
    'pdec.airport.train.price':'~25 Min. — ~4,50 €','pdec.airport.train.for':'Die günstigste Option',
    'pdec.airport.bus.title':'Bus Vienna Airport Lines',
    'pdec.airport.bus.desc':'Direktverbindungen zu mehreren Punkten im Stadtzentrum.',
    'pdec.airport.bus.price':'~20 bis 30 Min. — ~8 bis 10,50 €','pdec.airport.bus.for':'Praktisch, wenn Ihr Hotel in der Nähe einer Haltestelle liegt',
    'pdec.airport.tip.badge':'Gut zu wissen','pdec.airport.tip':'Bei Ankunft nach 23 Uhr empfiehlt sich ein Taxi — die öffentlichen Verkehrsmittel sind nachts eingeschränkt.',
    'pdec.price.lbl':'Richtpreis','pdec.for.lbl':'Für wen',
    'pdec.mob.badge':'Mobilität','pdec.mob.title':'Sich in Wien fortbewegen',
    'pdec.mob.tickets.title':'Tickets kaufen',
    'pdec.mob.tickets.desc':'Tickets können online im WienMobil Ticketshop oder an den Automaten in den Stationen gekauft werden (für mehr Komfort Englisch auswählen).',
    'pdec.mob.table.ticket':'Ticket','pdec.mob.table.price':'Preis (2026)',
    'pdec.mob.table.single':'Einzelfahrt','pdec.mob.table.single.val':'3,20 € Papier / 3,00 € App',
    'pdec.mob.table.day':'24-Stunden-Karte','pdec.mob.table.day.val':'10,20 €',
    'pdec.mob.table.week':'7-Tage-Ticket digital','pdec.mob.table.week.val':'25,20 €',
    'pdec.mob.table.citycard':'Vienna City Card (24h)','pdec.mob.table.citycard.val':'ab ca. 19 €',
    'pdec.mob.rule.badge':'Goldene Regel',
    'pdec.mob.rule.text':'Entwerten Sie Ihr Papierticket vor dem Einsteigen an den blauen Entwertern — digitale Tickets (App/online) sind automatisch gültig. Strafe bei Kontrolle ohne gültiges Ticket: 135 €.',
    'pdec.mob.airport.note':'⚠️ Der Flughafen liegt außerhalb der Kernzone (Zone 100): Ein Stadtticket allein reicht nicht aus — es ist ein Außenzonenzuschlag (~2,20 €) oder ein spezielles Flughafenticket erforderlich.',
    'pdec.mob.app.badge':'Empfohlene App','pdec.mob.app.title':'Laden Sie die WienMobil-App herunter',
    'pdec.mob.app.desc':'Die offizielle App der Wiener Linien ermöglicht den Ticketkauf (günstiger als Papier), Echtzeit-Routenplanung und die Reservierung von Leihfahrrädern.',
    'pdec.mob.app.appstore':'App Store','pdec.mob.app.googleplay':'Google Play',
    'pdec.mob.other.title':'Weitere Mobilitätsangebote',
    'pdec.mob.other.li1':'WienMobil Rad — Leihfahrräder, reservierbar über die App',
    'pdec.mob.other.li2':'Dichtes Netz: 5 U-Bahn-Linien, Straßenbahnen, Busse und S-Bahn',
    'pdec.mob.other.li3':'Nachtbusse am Wochenende für die sichere Heimfahrt',
    'pdec.fees.note':'Richtpreise (2026) — aktuelle Tarife finden Sie auf',
    'pdec.hotels.badge':'Unterkunft','pdec.hotels.title':'Wo man in Wien übernachten kann',
    'pdec.hotels.desc':'Eine indikative Auswahl an Unterkünften nach Budget, um Ihren Aufenthalt in Wien zu planen.',
    'pdec.hotels.budget.title':'Günstig / Hostels','pdec.hotels.mid.title':'Mittelklasse / Gehoben','pdec.hotels.top.title':'Gehobene Kategorie',
    'pdec.hotels.more':'Weitere Hotels in Wien ansehen →',
    'pdec.disclaimer':'Die genannten Einrichtungen und Dienste werden nur zu Informationszwecken angegeben. Die Botschaft empfiehlt oder garantiert keine privaten Anbieter. Richtpreise können sich ändern.',
    'pdec.food.badge':'Essen','pdec.food.title':'Essen in Wien',
    'pdec.food.delivery.title':'Online bestellen','pdec.food.delivery.desc':'In Wien stehen mehrere Lieferdienste zur Verfügung:',
    'pdec.food.african.title':'Afrikanische & westafrikanische Küche',
    'pdec.food.african.desc':'Für die Aromen der Heimat — Jollof Rice, Mafé, gegrilltes Hühnchen, Attiéké:',
    'pdec.food.viennese.title':'Wiener Spezialitäten zum Probieren',
    'pdec.food.viennese.desc':'Wiener Schnitzel, Sachertorte, Apfelstrudel — und ein Besuch am Naschmarkt für lokale Aromen.',
    'pdec.sights.badge':'Besichtigen','pdec.sights.title':'Sehenswürdigkeiten in Wien',
    'pdec.sights.desc':'Einige der bekanntesten Sehenswürdigkeiten für Ihren Aufenthalt.',
    'pdec.sights.schoenbrunn.title':'Schloss Schönbrunn','pdec.sights.schoenbrunn.desc':'Ehemalige kaiserliche Sommerresidenz mit UNESCO-geschütztem Garten.',
    'pdec.sights.hofburg.title':'Hofburg','pdec.sights.hofburg.desc':'Ehemaliger Regierungssitz der Habsburger, mitten im Herzen Wiens.',
    'pdec.sights.stephansdom.title':'Stephansdom','pdec.sights.stephansdom.desc':'Wiens Wahrzeichen mit gotischem Turm und Aussichtsplattform.',
    'pdec.sights.belvedere.title':'Schloss & Museum Belvedere','pdec.sights.belvedere.desc':'Beherbergt „Der Kuss" von Gustav Klimt und prächtige Barockgärten.',
    'pdec.sights.prater.title':'Der Prater','pdec.sights.prater.desc':'Berühmter Vergnügungspark mit dem historischen Riesenrad.',
    'pdec.sights.ring.title':'Ringstraße','pdec.sights.ring.desc':'Der große Ringboulevard mit Staatsoper, Parlament und Rathaus.',
    'pdec.sights.museumsquartier.title':'MuseumsQuartier','pdec.sights.museumsquartier.desc':'Eines der größten Kulturareale der Welt: Museen und Treffpunkte.',
    'pdec.sights.more':'Offizielles Tourismusbüro — vienna.info →',
    'pdec.practical.badge':'Damit nichts fehlt','pdec.practical.title':'Praktische Informationen',
    'pdec.practical.emergency.title':'Notrufnummern',
    'pdec.practical.emergency.eu':'Europäischer Notruf','pdec.practical.emergency.police':'Polizei',
    'pdec.practical.emergency.fire':'Feuerwehr','pdec.practical.emergency.ambulance':'Rettung',
    'pdec.practical.health.title':'Gesundheit',
    'pdec.practical.health.desc':'Apotheken (grünes Kreuz); die Bereitschaftsapotheke wird an der Tür jeder geschlossenen Apotheke angezeigt. Denken Sie an Ihre europäische Krankenversicherungskarte oder eine Reiseversicherung.',
    'pdec.practical.money.title':'Geld','pdec.practical.money.desc':'Geldautomaten (Bankomat) sind weit verbreitet, kontaktloses Zahlen ist üblich. Übliches Trinkgeld: 5 bis 10 %.',
    'pdec.practical.conn.title':'Konnektivität','pdec.practical.conn.desc':'Lokale SIM-Karten erhältlich bei A1, Magenta, Drei oder HoT. Öffentliches WLAN an vielen Orten.',
    'pdec.practical.weather.title':'Wetter & beste Reisezeit','pdec.practical.weather.desc':'Frühling und Herbst sind die angenehmsten Jahreszeiten. Der Winter ist kalt (Christkindlmärkte), der Sommer warm und sonnig.',
    'pdec.practical.german.title':'Nützliche deutsche Wörter',
    'pdec.practical.german.li1':'Grüß Gott — Hallo','pdec.practical.german.li2':'Danke — Danke',
    'pdec.practical.german.li3':'Bitte — Bitte / Gerne','pdec.practical.german.li4':'Entschuldigung — Entschuldigung',
    'pdec.practical.german.li5':'Wie viel? — Wie viel kostet das?',
    'pdec.practical.etiquette.title':'Etikette & Alltag',
    'pdec.practical.etiquette.desc':'Pünktlichkeit wird sehr geschätzt. Geschäfte sind sonntags meist geschlossen. Mülltrennung wird streng eingehalten, in öffentlichen Verkehrsmitteln ist Ruhe üblich.',
    'pdec.practical.excursions.title':'Ausflüge ab Wien',
    'pdec.practical.excursions.desc':'Bratislava (~1 Std.), die Wachau, Salzburg oder Graz sind mit der ÖBB bequem zu erreichen.',
    'pdec.practical.diaspora.title':'Ivorische Gemeinschaft & Diaspora',
    'pdec.practical.diaspora.desc':'Kontaktieren Sie die Botschaft oder folgen Sie unseren sozialen Netzwerken, um über Veranstaltungen der ivorischen Gemeinschaft in Österreich informiert zu bleiben.',
    'pdec.cta.title':'Eine Frage zu Ihrem Aufenthalt?',
    'pdec.cta.desc':'Unser Team steht Ihnen vor und während Ihres Aufenthalts in Österreich gerne zur Verfügung.',
    'pdec.cta.btn.whatsapp':'Über WhatsApp kontaktieren','pdec.cta.btn.contact':'Kontaktseite','pdec.cta.btn.rdv':'Termin vereinbaren',
  },

  en: {
    /* ── Navigation & chrome ── */
    'nav.home':'Home','nav.embassy':'Embassy','nav.services':'Services',
    'nav.annonces':'Announcements','nav.contact':'Contact',
    'logo.name':"Embassy of Côte d'Ivoire",
    'logo.sub':'Vienna, Austria',
    'footer.copy':"© 2025 Embassy of the Republic of Côte d'Ivoire in Austria",
    'footer.links.home':'Home','footer.links.embassy':'Embassy',
    'footer.links.services':'Services','footer.links.annonces':'Announcements',
    'footer.links.contact':'Contact',

    /* ── Top bar ── */
    'topbar.address':'Michael-Neumann-Gasse 2 - 3rd Floor, 1190 Vienna',
    'topbar.hours':'Mon–Fri : 9:30 AM – 4:00 PM',

    /* ── Alert ── */
    'alert.text':'Appointment required for all procedures.',
    'alert.link':'Book now →',

    /* ── Hero ── */
    'hero.tag':'Consular Service',
    'hero.h1':"Welcome to the Embassy of<br><em>Côte d'Ivoire</em>",
    'hero.desc':"Your consular services from Vienna, covering 8 Central European countries.",
    'hero.btn1':'Our Services','hero.btn2':'Book Appointment',
    'hero.countries':'9 countries served',
    'hero.floor':'1190 Vienna, 3rd Floor',

    /* ── Index — Services grid ── */
    'badge.services':'Our Services',
    'srv.title':'Consular Services','srv.more':'View →',
    'srv.passport':'Passport','srv.passport.sub':'Application & renewal',
    'srv.visa':'Visa','srv.visa.sub':'Tourism, business, transit',
    'srv.civil':'Civil Status','srv.civil.sub':'Acts & transcriptions',
    'srv.legal':'Legalisation','srv.legal.sub':'Official documents',
    'srv.cert':'Certificates','srv.cert.sub':'Life, residence, nationality',
    'srv.wa':'WhatsApp','srv.wa.sub':'Direct contact',

    /* ── Index — Infos pratiques ── */
    'badge.contact':'Contact',
    'info.practical':'Practical Information',
    'info.contact.title':'Contact us',
    'info.address.label':'Address',
    'info.phone.label':'Phone',
    'info.email.label':'Email',
    'info.emergency.label':'Emergency 24/7',

    /* ── Index — Pays ── */
    'badge.jurisdiction':'Jurisdiction',
    'pays.title':'Diplomatic Constituency',
    'pays.sub':'9 countries in Central Europe and the Balkans',
    'pays.at':'Austria','pays.hu':'Hungary','pays.si':'Slovenia',
    'pays.sk':'Slovakia','pays.hr':'Croatia','pays.rs':'Serbia',
    'pays.ro':'Romania','pays.ba':'Bosnia',

    /* ── Index — Actualités ── */
    'badge.news':'News',
    'actu.title':'Information & Announcements',
    'actu.tag1':'Economic mission',
    'actu.h3':"Visit of the President of the Economic, Social, Environmental and Cultural Council",
    'actu.p1':"Economic mission to strengthen ties between Côte d'Ivoire and Central Europe.",
    'actu.date1':'02 June 2025',
    'actu.month1':'May',
    'news1.title':'New passport application form',
    'news1.desc':'Update of the biometric application form.',
    'news2.title':'Closure — Labour Day',
    'news2.desc':'Closed on 1 May 2025.',

    /* ── CTA ── */
    'cta.title':'Need consular assistance?',
    'cta.desc':'File submission and collection Tuesday to Friday — by appointment.',
    'cta.btn':'Book an Appointment',
    'cta.call':'+43 1 581007610',

    /* ── Services page ── */
    'srv.breadcrumb':'Services',
    'srv.page.h1':'Consular Services',
    'srv.page.sub':'All your official administrative procedures',
    'info.rdv':'Appointment required','info.rdv.sub':'No procedure without appointment',
    'info.payment':'Online payment','info.payment.sub':'Online only',
    'info.delay':'Variable delays','info.delay.sub':'Depending on procedure',
    'info.file':'Complete file','info.file.sub':'All documents required',
    'badge.passport':'Travel document',
    'srv.passport.title':'Biometric Passport',
    'srv.pp.new':'First application','srv.pp.new.sub':'For persons without a passport',
    'srv.pp.renew':'Renewal','srv.pp.renew.sub':'Expired or to-be-renewed passport',
    'srv.pp.urgent':'Emergency passport','srv.pp.urgent.sub':'Loss, theft or emergency',
    'srv.fees':'Consular fees',
    'srv.delay.std':'Processing time: 4 to 8 weeks',
    'srv.delay.urgent':'Processing time: 24 to 72h',
    /* Première demande */
    'pp.new.req1':"Original birth certificate (less than 3 months old)",
    'pp.new.req2':"Ivorian nationality certificate",
    'pp.new.req3':"2 identity photos (white background, 35×45mm)",
    'pp.new.req4':"Proof of residence",
    /* Renouvellement */
    'pp.renew.req1':"Original old passport",
    'pp.renew.req2':"Birth certificate (less than 3 months old)",
    'pp.renew.req3':"2 recent identity photos",
    /* Urgence */
    'pp.urgent.req1':"Loss/theft report (police)",
    'pp.urgent.req2':"Original birth certificate",
    'pp.urgent.req3':"Proof of urgency",
    /* Visa touristique */
    'visa.tourist.req1':"Valid passport (min. 6 months)",
    'visa.tourist.req2':"Return flight ticket",
    'visa.tourist.req3':"Proof of accommodation",
    'visa.tourist.req4':"Travel insurance",
    /* Visa affaires */
    'visa.business.req1':"Valid passport",
    'visa.business.req2':"Invitation letter from an Ivorian company",
    'visa.business.req3':"Company registration extract",
    'badge.visa':'Entry visa',
    'srv.visa.title':"Visa for Côte d'Ivoire",
    'srv.visa.tourist':'Tourist visa','srv.visa.tourist.sub':'Stay up to 90 days',
    'srv.visa.business':'Business visa','srv.visa.business.sub':'Professional activities',
    'srv.visa.fees':'Visa fees',
    'srv.delay.visa':'Processing time: 5 to 10 business days',
    'badge.civil':'Civil Status',
    'srv.civil.title':'Civil records',
    'srv.civil.online':'Available documents','srv.civil.online.sub':'Click to pay online',
    'civil.act.death':'Death certificate',
    'civil.act.marriage':'Marriage certificate',
    'civil.act.admin':'Administrative attestation',
    'civil.act.id':'Consular identity card',
    'civil.act.wed':'Wedding ceremony',
    'civil.act.life':'Certificate of life',
    'civil.act.birth':'Birth certificate extract',
    'civil.act.pass':'Voluntary travel document',
    'civil.act.legal.admin':'Legalisation admin. documents',
    'civil.act.legal.co':'Legalisation for companies',
    'civil.act.transcription':'Transcription of civil records',
    'badge.cert':'Certificates',
    'srv.cert.title':'Certificates & Attestations',
    'srv.cert.online':'Consular certificates','srv.cert.online.sub':'Online payment',
    'cert.life':'Certificate of life',
    'cert.single':'Certificate of single status',
    'cert.residence':'Certificate of residence',
    'cert.nationality':'Certificate of nationality',
    'cert.custom':'Certificate of customary law',
    'cert.proxy':'Power of attorney',
    'badge.faq':'FAQ',
    'srv.faq.title':'Frequently asked questions',
    'faq1.q':'Is an appointment required?',
    'faq1.a':'Yes, booking an appointment is mandatory for all file submissions. Contact us by phone or email.',
    'faq2.q':'Passport processing time?',
    'faq2.a':'Generally 4 to 8 weeks. Emergency: 24 to 72 hours depending on the situation.',
    'faq3.q':'I live in Hungary, can I come to Vienna?',
    'faq3.a':'Yes. The Embassy covers 9 countries: Austria, Hungary, Slovenia, Slovakia, Croatia, Serbia, Romania and Bosnia-Herzegovina.',
    'srv.cta.title':'Ready to get started?',
    'srv.cta.desc':'Book an appointment or pay your consular fees online.',
    'btn.rdv':'Book an appointment','btn.call':'Call',

    /* ── Ambassade page ── */
    'amb.breadcrumb':'Embassy',
    'amb.h1':"The Embassy of Côte d'Ivoire",
    'amb.sub':'Official representation in Austria from Vienna',
    'amb.stat.countries':'countries in the constituency',
    'amb.stat.conv':'Vienna Convention',
    'amb.stat.ci':"Côte d'Ivoire",
    'amb.stat.host':'Host country',
    'badge.mission':'Our Mission',
    'amb.mission.title':'Diplomatic & Consular Mission',
    'amb.mission.p1':"The Embassy of the Republic of Côte d'Ivoire in Austria is the official diplomatic representation of Côte d'Ivoire in Vienna. It defends Ivorian interests, develops bilateral relations and protects its nationals.",
    'amb.mission.p2':"Established under the Vienna Convention of 1961, the Embassy fulfils a dual mission: diplomatic and consular.",
    'badge.direction':'Leadership',
    'amb.title':"Ambassador Extraordinary and Plenipotentiary of the Republic of Côte d'Ivoire in Austria",
    'amb.p1':"His Excellency Mr Cissé Yacouba has been accredited to the Republic of Austria since 2023. He is also accredited to Hungary, Slovenia, Slovakia, Croatia, Serbia, Romania and Bosnia-Herzegovina.",
    'amb.p2':"With a long diplomatic career, His Excellency represents the interests of the Ivorian Republic and coordinates all the Embassy's services.",
    'badge.diplomacy':'Diplomacy',
    'amb.rel.title':'CI — Austria Relations',
    'rel.bilateral.title':'Bilateral cooperation',
    'rel.bilateral.desc':'Relations based on mutual respect, economic, cultural and educational cooperation.',
    'rel.trade.title':'Trade relations',
    'rel.trade.desc':"CI exports cocoa, coffee and raw materials. Austria is a partner in industry and services.",
    'rel.academic.title':'Academic cooperation',
    'rel.academic.desc':'University exchanges and scholarship programmes for Ivorian students.',
    'rel.intl.title':'International organisations',
    'rel.intl.desc':'Vienna hosts UNIDO, IAEA, UNODC. The Embassy coordinates Ivorian participation.',
    'badge.ci':"Côte d'Ivoire",
    'ci.title':"Discover Côte d'Ivoire",
    'ci.area':'Area','ci.pop':'Population',
    'ci.indep':'Independence','ci.capital':'Capital',
    'amb.cta.title':'Need a service?',
    'amb.cta.desc':'Our team is available Monday to Friday.',
    'amb.cta.btn1':'View services','amb.cta.btn2':'Contact us',

    /* ── Contact page ── */
    'contact.breadcrumb':'Contact',
    'contact.h1':'Contact & Hours',
    'contact.sub':'Contact details and hours of the consular service',
    'contact.phone.label':'Phone','contact.email.label':'Email',
    'contact.address.label':'Address','contact.emergency.label':'Emergencies',
    'contact.address.val':'1190 Vienna, 3rd Floor',
    'badge.hours':'Consular Hours',
    'contact.hours.title':'Opening hours',
    'contact.hours.sub':'By appointment only',
    'table.day':'Day','table.counter':'Counter',
    'contact.holidays':'Public holidays (selection)',
    'holiday.newyear':'New Year\'s Day','holiday.labor':'Labour Day',
    'holiday.ci':'National Day CI','holiday.at':'National Day AT',
    'badge.access':'Getting here',
    'contact.addr.title':'Address',
    'contact.floor':'3rd Floor — 1190 Vienna, Austria',
    'contact.metro':'Metro','contact.metro.val':'U4 — Heiligenstadt station',
    'contact.bus':'Bus','contact.bus.val':'Line 35A — Michael-Neumann-Gasse stop',
    'contact.maps':'Open in Google Maps →',
    'badge.form':'Send a message',
    'contact.form.title':'Contact form',
    'form.firstname':'First name','form.lastname':'Last name','form.email':'Email',
    'form.phone':'Phone','form.country':'Country of residence',
    'form.country.select':'— Select —',
    'form.subject':'Subject','form.subject.select':'— Type of request —',
    'form.rdv':'Appointment booking','form.passport':'Passport','form.visa':'Visa',
    'form.civil':'Civil status','form.emergency':'Consular emergency',
    'form.message':'Message','form.placeholder':'Describe your request...',
    'form.submit':'Send →',
    'contact.urgency.title':'Consular emergencies',
    'contact.urgency.text':'In case of emergency outside opening hours (lost passport, death, hospitalisation, arrest), our on-call service is available 24/7.',

    /* ── Annonces page ── */
    'annonces.breadcrumb':'Announcements',
    'annonces.h1':'Information & Announcements',
    'annonces.sub':'Official notices, closures, events and press releases',
    'annonces.pinned':'Pinned — Urgent',
    'annonces.pin.title':"Closure — National Day of Côte d'Ivoire",
    'annonces.pin.text':'The Embassy will be <strong>closed on Monday 7 August 2025</strong> for the National Day (65th anniversary). Services resume Tuesday 8 August at 9:30 AM.',
    'annonces.pin.date':'Published 10 July 2025',
    'filter.all':'All','filter.urgent':'Urgent',
    'filter.admin':'Administrative','filter.event':'Events',
    'filter.communique':'Press releases',
    /* Categories */
    'cat.urgent':'Urgent','cat.admin':'Administrative',
    'cat.event':'Event','cat.communique':'Press release',
    /* Annonce 1 */
    'ann1.date':'15 July 2025',
    'ann1.title':'Disruption — Renovation works',
    'ann1.text':'Services disrupted from <strong>21 to 25 July</strong>. File submissions by appointment only.',
    'btn.rdv.short':'Book appointment','btn.write':'Write',
    /* Annonce 2 */
    'ann2.date':'1 July 2025',
    'ann2.title':'New consular fees — 1 August 2025',
    'ann2.text':'The new consular fee schedule takes effect on <strong>1 August 2025</strong>.',
    'btn.download':'Download PDF','btn.services':'Services',
    /* Annonce 3 */
    'ann3.date':'20 June 2025',
    'ann3.title':'Mobile Consular Day — Budapest, 12 Sept.',
    'ann3.text':'Administrative procedures on-site in Budapest. Registration before <strong>29 August 2025</strong>.',
    'btn.register':'Register','btn.programme':'Programme',
    /* Annonce 4 */
    'ann4.date':'5 June 2025',
    'ann4.title':'Reminder — Documents required for passport',
    'ann4.text':'Old passport, legalised birth certificate, 2 photos, proof of address. Incomplete files will be returned.',
    'btn.procedure':'Full procedure',
    /* Annonce 5 */
    'ann5.date':'15 May 2025',
    'ann5.title':'Presentation of credentials',
    'ann5.text':'H.E. Mr Cissé Yacouba presented his credentials to the Austrian Federal President at the Hofburg Palace.',
    'btn.read':'Read the press release',
    'annonce.subscribe.title':'Receive announcements',
    'annonce.subscribe.desc':'Sign up to be notified of new important information.',
    'annonce.subscribe.placeholder':'your@email.com',
    'annonce.subscribe.btn':'OK →',
    'annonce.follow':'Follow us',
    'annonce.empty':'No announcement in this category.',

    /* ── Days ── */
    'day.mon':'Monday','day.tue':'Tuesday','day.wed':'Wednesday','day.thu':'Thursday',
    'day.fri':'Friday','day.sat':'Saturday','day.sun':'Sunday','day.closed':'Closed',
    'hours.val':'9:30 AM – 4:00 PM',
    'hours.depot':'File submission',
    'hours.retrait':'File collection',
    'hours.rdv':'(by appointment)',
    'hours.days':'Tuesday – Friday',
    'hours.depot.time':'9:00 AM – 2:00 PM',
    'hours.retrait.time':'2:00 PM – 4:00 PM',
    'hours.closed.days':'Mon. · Sat. · Sun.',

    /* ── Discover Austria ── */
    'nav.discover':'Discover',
    'pdec.badge':'Practical Guide','pdec.h1':'Discover Austria',
    'pdec.desc':"Whether you're visiting for a few days or settled in Austria long-term, this practical guide helps you make the most of Vienna: transport, accommodation, dining, sightseeing and useful information.",
    'pdec.toc.airport':'Airport','pdec.toc.mobility':'Transport','pdec.toc.hotels':'Accommodation',
    'pdec.toc.food':'Dining','pdec.toc.sights':'Sightseeing','pdec.toc.practical':'Practical Info',
    'pdec.airport.badge':'Arriving in Vienna','pdec.airport.title':'Arrival at Vienna Airport (VIE)',
    'pdec.airport.intro':'Vienna International Airport is located about 18 to 20 km from the city centre, which takes 20 to 30 minutes depending on the option chosen.',
    'pdec.airport.taxi.title':'Taxi / Private Transfer',
    'pdec.airport.taxi.desc':'Official taxi rank in front of the arrivals area (plates ending in "TX", illuminated roof sign).',
    'pdec.airport.taxi.li1':'Taxi 40100 — airport flat rate ~€42 (mention "airport transfer" when booking)',
    'pdec.airport.taxi.li2':'Taxi 31300 — flat rate ~€37 via the app',
    'pdec.airport.taxi.li3':'Ride-hailing apps: Bolt, Uber, FREE NOW (~€19 to €57)',
    'pdec.airport.taxi.price':'~€35 to €50 on the meter','pdec.airport.taxi.for':'Ideal with luggage or in a group',
    'pdec.airport.cat.title':'City Airport Train (CAT)',
    'pdec.airport.cat.desc':'Non-stop direct train between the airport and Wien Mitte.',
    'pdec.airport.cat.price':'16 min — ~€11 to €14.90','pdec.airport.cat.for':'Ideal for a fast, comfortable ride',
    'pdec.airport.train.title':'S7 Train (ÖBB)',
    'pdec.airport.train.desc':'Regional train linking the airport to the city centre, with several stops.',
    'pdec.airport.train.price':'~25 min — ~€4.50','pdec.airport.train.for':'The cheapest option',
    'pdec.airport.bus.title':'Vienna Airport Lines Bus',
    'pdec.airport.bus.desc':'Direct connections to several points in the city centre.',
    'pdec.airport.bus.price':'~20 to 30 min — ~€8 to €10.50','pdec.airport.bus.for':'Handy if your hotel is near a stop',
    'pdec.airport.tip.badge':'Good to know','pdec.airport.tip':'If arriving after 11pm, a taxi is recommended — public transport is limited at night.',
    'pdec.price.lbl':'Indicative price','pdec.for.lbl':'Best for',
    'pdec.mob.badge':'Getting Around','pdec.mob.title':'Getting around Vienna',
    'pdec.mob.tickets.title':'Buying your ticket',
    'pdec.mob.tickets.desc':'Tickets can be bought online via the WienMobil Ticketshop or from machines at stations (select English for ease of use).',
    'pdec.mob.table.ticket':'Ticket','pdec.mob.table.price':'Price (2026)',
    'pdec.mob.table.single':'Single trip (Einzelfahrt)','pdec.mob.table.single.val':'€3.20 paper / €3.00 app',
    'pdec.mob.table.day':'24-hour pass','pdec.mob.table.day.val':'€10.20',
    'pdec.mob.table.week':'7-day digital ticket','pdec.mob.table.week.val':'€25.20',
    'pdec.mob.table.citycard':'Vienna City Card (24h)','pdec.mob.table.citycard.val':'from ~€19',
    'pdec.mob.rule.badge':'Golden rule',
    'pdec.mob.rule.text':'Validate your paper ticket at the blue validators before boarding — digital tickets (app/online) are automatically valid. Fine for travelling without a valid ticket: €135.',
    'pdec.mob.airport.note':'⚠️ The airport is outside the central zone (Zone 100): a city ticket alone is not enough — you need an outer zone supplement (~€2.20) or a specific airport ticket.',
    'pdec.mob.app.badge':'Recommended app','pdec.mob.app.title':'Download the WienMobil app',
    'pdec.mob.app.desc':'The official Wiener Linien app lets you buy tickets (cheaper than paper), plan routes in real time, and book shared bikes.',
    'pdec.mob.app.appstore':'App Store','pdec.mob.app.googleplay':'Google Play',
    'pdec.mob.other.title':'Other mobility options',
    'pdec.mob.other.li1':'WienMobil Rad shared bikes, bookable via the app',
    'pdec.mob.other.li2':'Dense network: 5 underground (U-Bahn) lines, trams, buses and S-Bahn',
    'pdec.mob.other.li3':'Night buses at weekends for a safe ride home',
    'pdec.fees.note':'Indicative prices (2026) — check current rates on',
    'pdec.hotels.badge':'Accommodation','pdec.hotels.title':'Where to stay in Vienna',
    'pdec.hotels.desc':'An indicative selection of accommodation by budget to help plan your stay in Vienna.',
    'pdec.hotels.budget.title':'Budget / Hostels','pdec.hotels.mid.title':'Mid-range / Upscale','pdec.hotels.top.title':'High-end',
    'pdec.hotels.more':'See more hotels in Vienna →',
    'pdec.disclaimer':'The establishments and services mentioned are provided for information only. The Embassy does not recommend or guarantee any private provider. Indicative prices are subject to change.',
    'pdec.food.badge':'Dining','pdec.food.title':'Eating in Vienna',
    'pdec.food.delivery.title':'Order online','pdec.food.delivery.desc':'Several food delivery platforms are available in Vienna:',
    'pdec.food.african.title':'African & West African cuisine',
    'pdec.food.african.desc':'For a taste of home — jollof rice, mafé, grilled chicken, attiéké:',
    'pdec.food.viennese.title':'Viennese specialities to try',
    'pdec.food.viennese.desc':'Wiener Schnitzel, Sachertorte, Apfelstrudel — and visit the Naschmarkt for local flavours.',
    'pdec.sights.badge':'Sightseeing','pdec.sights.title':'Must-see sights in Vienna',
    'pdec.sights.desc':'Some iconic sights to discover during your stay.',
    'pdec.sights.schoenbrunn.title':'Schönbrunn Palace','pdec.sights.schoenbrunn.desc':'Former imperial summer residence with UNESCO-listed gardens.',
    'pdec.sights.hofburg.title':'Hofburg Palace','pdec.sights.hofburg.desc':'The former seat of Habsburg power, in the heart of Vienna.',
    'pdec.sights.stephansdom.title':"St. Stephen's Cathedral",'pdec.sights.stephansdom.desc':"Vienna's iconic symbol, with its gothic spire and panoramic tower.",
    'pdec.sights.belvedere.title':'Belvedere Palace & Museum','pdec.sights.belvedere.desc':'Home to Gustav Klimt\'s "The Kiss" and stunning baroque gardens.',
    'pdec.sights.prater.title':'The Prater','pdec.sights.prater.desc':'Famous amusement park and its historic Ferris wheel, the Riesenrad.',
    'pdec.sights.ring.title':'Ringstrasse','pdec.sights.ring.desc':'The grand ring boulevard linking the Opera House, Parliament and City Hall.',
    'pdec.sights.museumsquartier.title':'MuseumsQuartier','pdec.sights.museumsquartier.desc':'One of the largest cultural districts in the world: museums and meeting places.',
    'pdec.sights.more':'Official tourist board — vienna.info →',
    'pdec.practical.badge':"So you don't miss anything",'pdec.practical.title':'Practical information',
    'pdec.practical.emergency.title':'Emergency numbers',
    'pdec.practical.emergency.eu':'European emergency number','pdec.practical.emergency.police':'Police',
    'pdec.practical.emergency.fire':'Fire brigade','pdec.practical.emergency.ambulance':'Ambulance',
    'pdec.practical.health.title':'Health',
    'pdec.practical.health.desc':'Pharmacies (Apotheke, green cross); the on-duty pharmacy is posted on the door of every closed pharmacy. Bring your European Health Insurance Card or travel insurance.',
    'pdec.practical.money.title':'Money','pdec.practical.money.desc':'ATMs (Bankomat) are widely available, contactless payment is common. Usual tip: 5 to 10%.',
    'pdec.practical.conn.title':'Connectivity','pdec.practical.conn.desc':'Local SIM cards available from A1, Magenta, Drei or HoT. Public WiFi in many places.',
    'pdec.practical.weather.title':'Weather & best time to visit','pdec.practical.weather.desc':'Spring and autumn are the most pleasant seasons. Winter is cold (Christmas markets), summer is warm and sunny.',
    'pdec.practical.german.title':'Useful German words',
    'pdec.practical.german.li1':'Grüß Gott — Hello','pdec.practical.german.li2':'Danke — Thank you',
    'pdec.practical.german.li3':"Bitte — Please / You're welcome",'pdec.practical.german.li4':'Entschuldigung — Excuse me / Sorry',
    'pdec.practical.german.li5':'Wie viel? — How much?',
    'pdec.practical.etiquette.title':'Etiquette & daily life',
    'pdec.practical.etiquette.desc':'Punctuality is highly valued. Shops are generally closed on Sundays. Waste sorting is strict and public transport tends to be quiet.',
    'pdec.practical.excursions.title':'Day trips from Vienna',
    'pdec.practical.excursions.desc':'Bratislava (~1h), the Wachau valley, Salzburg or Graz are easily reached by train via ÖBB.',
    'pdec.practical.diaspora.title':'Ivorian community & diaspora',
    'pdec.practical.diaspora.desc':'Contact the Embassy or follow our social media for updates on Ivorian community events in Austria.',
    'pdec.cta.title':'A question about your stay?',
    'pdec.cta.desc':'Our team is available to assist you before and during your stay in Austria.',
    'pdec.cta.btn.whatsapp':'Contact us on WhatsApp','pdec.cta.btn.contact':'Contact Page','pdec.cta.btn.rdv':'Book an Appointment',
  }
};

/* ── i18n placeholders ── */
function setLang(lang) {
  if (!T[lang]) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const k = el.dataset.i18n;
    if (T[lang][k] !== undefined) el.textContent = T[lang][k];
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const k = el.dataset.i18nHtml;
    if (T[lang][k] !== undefined) el.innerHTML = T[lang][k];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const k = el.dataset.i18nPh;
    if (T[lang][k] !== undefined) el.placeholder = T[lang][k];
  });
  document.querySelectorAll('.m-lang-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.lang === lang);
  });
  document.documentElement.lang = lang;
  localStorage.setItem('ambaci-mobile-lang', lang);
}

(function init() {
  const lang = localStorage.getItem('ambaci-mobile-lang') || 'fr';
  setLang(lang);

  /* Accordion */
  document.querySelectorAll('.m-acc-trigger').forEach(t => {
    t.addEventListener('click', () => {
      const panel = document.getElementById(t.getAttribute('aria-controls'));
      const open = t.getAttribute('aria-expanded') === 'true';
      document.querySelectorAll('.m-acc-trigger').forEach(x => {
        x.setAttribute('aria-expanded','false');
        const p = document.getElementById(x.getAttribute('aria-controls'));
        if (p) p.classList.remove('open');
      });
      if (!open && panel) { t.setAttribute('aria-expanded','true'); panel.classList.add('open'); }
    });
  });

  /* Alert close */
  const alertClose = document.getElementById('m-alert-close');
  const alertBanner = document.getElementById('m-alert');
  if (alertClose && alertBanner) {
    alertClose.addEventListener('click', () => { alertBanner.style.display = 'none'; });
  }

  /* Highlight today in schedule table */
  const days = ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
  const today = days[new Date().getDay()];
  document.querySelectorAll('.m-table tbody tr').forEach(row => {
    if (row.querySelector('td')?.textContent.trim() === today) row.classList.add('today');
  });

  /* Contact form */
  const form = document.getElementById('m-contact-form');
  if (form) {
    form.addEventListener('submit', e => {
      e.preventDefault();
      const btn = form.querySelector('[type="submit"]');
      btn.disabled = true; btn.textContent = '…';
      setTimeout(() => {
        btn.textContent = '✓'; btn.style.background = '#009A44';
        form.reset();
        setTimeout(() => { btn.disabled=false; btn.textContent='→'; btn.style.background=''; }, 3500);
      }, 1400);
    });
  }
})();

/* ── Hamburger / side drawer ── */
(function () {
  var btn = document.getElementById('m-hamburger');
  var drawer = document.getElementById('m-drawer');
  var overlay = document.getElementById('m-drawer-overlay');
  var closeBtn = document.getElementById('m-drawer-close');
  if (!btn || !drawer) return;

  function open() {
    drawer.classList.add('open');
    overlay.classList.add('open');
    btn.classList.add('open');
    btn.setAttribute('aria-expanded', 'true');
    document.body.style.overflow = 'hidden';
  }
  function close() {
    drawer.classList.remove('open');
    overlay.classList.remove('open');
    btn.classList.remove('open');
    btn.setAttribute('aria-expanded', 'false');
    document.body.style.overflow = '';
  }
  btn.addEventListener('click', open);
  if (closeBtn) closeBtn.addEventListener('click', close);
  overlay.addEventListener('click', close);
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });
})();

